### ISSUE TITLE
CEX in Interprocedural SeaHorn

### ISSUE THREAD

**Issue by lememta** [seahorn/seahorn#1]
Support for printing CEX.

**Comment by agurfinkel** [comment]
I asked Anvesh to look into this.

On Monday, March 16, 2015, lememta <notifications@github.com> wrote:

> Support for printing CEX.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/seahorn/seahorn/issues/1>.
>


-- 
On the move ...
