### ISSUE TITLE
Incorrect CHC

### ISSUE THREAD

**Issue by caterinaurban** [seahorn/seahorn#10]
The `sea smt` script generates incorrect CHC for the following C program:

    extern void __SEAHORN_fail (void);
    int main() {
        int y = 42;
        int x = 84;
        while (x >= 0) {
                y = 2*y - x;
                x = (y + x) / 2;
        }		
        __SEAHORN_fail();
        return 0;
    }

The .ll file resulting from 

`sea smt -o weird.smt2 weird.c -O0 --step=flarge --oll=weird.ll`

is fine. In particular the loop body is simplified to this:

```
_y.0:                                             ; preds = %_4, %_br
  %y.0 = phi i32 [ 42, %_br ], [ %_br2, %_4 ]
  %x.0 = phi i32 [ 84, %_br ], [ %y.0, %_4 ]
  %_br1 = icmp sgt i32 %x.0, -1
  br i1 %_br1, label %_4, label %_call

_4:                                               ; preds = %_y.0
  %_5 = mul nsw i32 %y.0, 2
  %_br2 = sub nsw i32 %_5, %x.0
  br label %_y.0
```

where, after renaming, y_new = 2*y_old - x_old and x_new = y_old.
However, the loop body in the .smt2 file becomes this

```
(rule (let ((a!1 (and (main_1 1 main@%y.0_0 main@%x.0_0)
                true
                (= main@%_br1_0 (> main@%x.0_0 (- 1)))
                (=> main@_4_0 (and main@_y.0_0 |tuple(main@_y.0_0, main@_4_0)|))
                (=> (and main@_y.0_0 |tuple(main@_y.0_0, main@_4_0)|)
                    main@%_br1_0)
                (=> main@_4_0 (= main@%_5_0 (* main@%y.0_0 2)))
                (=> main@_4_0 (= main@%_br2_0 (- main@%_5_0 main@%x.0_0)))
                (=> main@_y.0_1 (and main@_4_0 |tuple(main@_4_0, main@_y.0_1)|))
                main@_y.0_1
                (=> (and main@_4_0 |tuple(main@_4_0, main@_y.0_1)|)
                    (= main@%y.0_1 main@%_br2_0))
                (=> (and main@_4_0 |tuple(main@_4_0, main@_y.0_1)|)
                    (= main@%x.0_1 main@%y.0_1))    <--- here it should be main@%y.0_0
                (=> (and main@_4_0 |tuple(main@_4_0, main@_y.0_1)|)
                    (= main@%y.0_2 main@%y.0_1))
                (=> (and main@_4_0 |tuple(main@_4_0, main@_y.0_1)|)
                    (= main@%x.0_2 main@%x.0_1)))))
  (=> a!1 (main_1 1 main@%y.0_2 main@%x.0_2))))
```

where, after renaming y_new = 2*y_old - x_old and x_new = y_new.
In particular the difference is between x_new = y_old (correct) and x_new = y_new (wrong).

**Comment by agurfinkel** [comment]
The smt encoding is correct. The issue (if anywhere) is with LLVM optimizations.

**Comment by agurfinkel** [comment]
This is actually a bug with SeaHorn interpretation of LLVM semantics. Phi-nodes must be interpreted atomically and not sequentially.

**Comment by agurfinkel** [comment]
Fixed in 362ba0
