### ISSUE TITLE
Supporting modular verification

### ISSUE THREAD

**Issue by ezudheen** [seahorn/seahorn#101]
I would like to incorporated modular verification in Seahorn, just like in Boogie verifier.
In order to verify the programs with the following structure

main()
requires;
ensures;
{
    call subRoutine(arg);
}

subRoutine(arg)
requires;
ensures;
{
     if (arg < 0) {
         return
     } else {
         call subRoutine();
}

I would like to generate the verification conditions (Assume/Guarantee + Hoare logic format) for the above program and pass them to the solver. Can you please let me know which are the files and methods I need to modify.

**Comment by caballa** [comment]
Currently, spacer (the main SeaHorn back-end solver) produces summaries per function.  You should be able to print those summaries as assume/guarantee contracts. 

However, right now we don't have an annotation language so that the user can provide require/ensure annotations. 

Are you talking about contract inference or contract annotations, or both?

**Comment by agurfinkel** [comment]
The first step is to propose a language for annotations. The easiest is to use special methods (like code contracts) to determine ensures and requires. The second step is to decide whether you require annotations on loops (i.e., inductive invariants). Both of these need to be integrated with the clang parser (if they actually change the language). The third step is to take these annotations into account during VC gen. This requires a new Symbolic Execution engine. We currently have several examples: the main one used for verification (UfoSymExec) and another used for Bmc (BvSymExec).

**Comment by ezudheen** [comment]
My requirement is to generate VCs which represent the entire program using deductive approach. In the present implementation of Seahorn. the loop invariant(even without explicitly specifying) is implicitly represented in smt2 encoding as a relation(uninterpreted function). Similarly, I would like to generate the relations corresponding to requires, ensures and the horn clauses to connect these relations. As per my understanding, I don't need to modify the language or annotations, But I need to modify the mixedSematics and Symbolic Execution engine. I would like to know how to modify the mixedSemantics?

**Comment by agurfinkel** [comment]
The current semantics generates predicates for each function call. We don't have separate predicates for requires and ensures. Instead, we use a single predicate for the summary, that basically corresponds to the implication `requires -> ensures`. Our Horn solver would not work well with a different encoding. If you do want two predicates per function, you would need to change VC gen (which is called symexec in our case). 

There is no need to change mixed semantics. It works at the level of bitcode and is independent of VCGen. If it interferes with your VC gen, you can simply disable it. It is optional even in SeaHorn case.

**Comment by ezudheen** [comment]
Thanks, let me try to figure it out. It will be very helpful for me if you can specify the files and locations (line numbers) for generating the modular VCs in stm2 encoding.

**Comment by agurfinkel** [comment]
`HornifyModule` glues the VC from all the functions
`HornifyFunction` constructs the VC for an individual function from VC of basic blocks
`SymExec` (and in particular `UfoSymExec`) construct VC of basic blocks

You would need to change `SymExec` to replaces function calls with requires/ensures. Currently, a function call is replaced by a single uninterpreted predicate (like loop heads).

You might need to change `HornifyFunction` to accommodate the new VC. Although it might no longer be Horn clauses. 

You might need to change `HornifyModule` depending of how VCs for the function are glued together. 

BTW: what is the reason for changing the encoding? What solver are you targeting?

**Comment by ezudheen** [comment]
1. We are verifying sequential and concurrent programs using Hoare logic and Rely-Guarantee techniques. Currently, I am using Boogie for generating VCs for sequential programs and generate manual VCs for concurrent programs. I am intrested in automating VC generation for conurrent programs. And I also realize that LLVM based VC encoding is more efficient than Boogie encoding.

2. We have developed a black box learning technique based solver for learning uninterpreted functions. This is an extension of ICE learning technique, the new solver can learn multiple invariants.
