### ISSUE TITLE
Problem when building Seahorn

### ISSUE THREAD

**Issue by Baha** [seahorn/seahorn#11]
I am trying to build Seahorn in Mac OS X (is this supposed to work?). I've installed LLVM and Boost dependencies and CMake does succesfully find them.

However, when I execute `cmake --build .` I obtain the following error:
```
[ 11%] Building CXX object lib/CMakeFiles/shadow.dir/Transforms/Instrumentation/ShadowMemDsa.cc.o
/Users/baha/seahorn/lib/Transforms/Instrumentation/ShadowMemDsa.cc:516:50: error: 
      unknown type name 'StripShadowMem'
  Pass * createStripShadowMemPass () {return new StripShadowMem ();}
                                                 ^
/Users/baha/seahorn/lib/Transforms/Instrumentation/ShadowMemDsa.cc:521:36: error: 
      no member named 'StripShadowMem' in namespace 'seahorn'
static llvm::RegisterPass<seahorn::StripShadowMem> Y ("strip-shadow-dsa",
                          ~~~~~~~~~^
2 errors generated.
make[2]: *** [lib/CMakeFiles/shadow.dir/Transforms/Instrumentation/ShadowMemDsa.cc.o] Error 1
make[1]: *** [lib/CMakeFiles/shadow.dir/all] Error 2
make: *** [all] Error 2
```

Maybe it is because you are commiting changes and I know it is not wise to build the master branch, but...

**Comment by agurfinkel** [comment]
Closed by 595f3c

First, you should let the build process build its own LLVM. We had strange issues with using externally-built LLVM.

Second, you are not compiling with the optional dependencies (make extra step in the instructions). While this is supported, the result might not be what you want, and this configuration is untested.
