### ISSUE TITLE
Understanding the generated CEX

### ISSUE THREAD

**Issue by Robbin1987** [seahorn/seahorn#111]
Hi Guys,

I am trying to understand how the generated counter-example is constructed and how I can find its return value (the value that makes the sassert fail).

So I have the following two functions as example:

```
int main()
{
    if(ValidateVal())
    {
    display();
    }
return 0;
}

int display()
{
 int x=addafter(1,1); int y=0;
 if(ValidateFunc()==10) {
   int t1 = x;
   int t2 = y;
   x = t1+ t2;
   y = t1 + t2;
  }
   sassert(y == 0);
   return 0;
}
```

Both ValidateVal and ValidateFunc are made external and are used for the verification.

The generated counter-example looks as follows:
`
@0 = private constant [1 x i32] zeroinitializer
@1 = private global i32 0
@2 = private constant [1 x i32] zeroinitializer
@3 = private global i32 0

define i32 @ValidateVal() {
entry:
  %0 = load i32* @1
  %1 = add i32 %0, 1
  store i32 %1, i32* @1
  %2 = call i32 @__seahorn_get_value_i32(i32 %0, i32* getelementptr inbounds ([1 x i32]* @0, i32 0, i32 0), i32 1)
  ret i32 %2
}

declare i32 @__seahorn_get_value_i32(i32, i32*, i32)

define i32 @ValidateFunc() {
entry:
  %0 = load i32* @3
  %1 = add i32 %0, 1
  store i32 %1, i32* @3
  %2 = call i32 @__seahorn_get_value_i32(i32 %0, i32* getelementptr inbounds ([1 x i32]* @2, i32 0, i32 0), i32 1)
  ret i32 %2
}
`

ValidateVal should return 1, and ValidateFunc should return 10 to make the assertion fail, but where is that value located. In the counter-example both functions are identical.

Thanks in advance,

**Comment by caballa** [comment]
I tried this program:

```
extern int nd(void);
extern void __VERIFIER_error(void) __attribute__((noreturn));
#define assert(X) if(!(X)){__VERIFIER_error();}

extern int ValidateFunc(void);
extern int ValidateVal(void);

int addafter(int x, int y) {
  return x+y;
}

int display()
{
 int x=addafter(1,1); int y=0;
 if(ValidateFunc()==10) {
   int t1 = x;
   int t2 = y;
   x = t1+ t2;
   y = t1 + t2;
  }
   assert(y == 0);
   return 0;
}

int main() {
  if(ValidateVal())
    display();
  return 0;
}
```
and the harness I get is:
``` 
; ModuleID = 'harness'
target datalayout = "e-m:o-p:32:32-f64:32:64-f80:128-n8:16:32-S128"

@0 = private constant [1 x i32] [i32 1]
@1 = private global i32 0
@2 = private constant [1 x i32] [i32 10]
@3 = private global i32 0

define i32 @ValidateVal() {
entry:
  %0 = load i32, i32* @1
  %1 = add i32 %0, 1
  store i32 %1, i32* @1
  %2 = call i32 @__seahorn_get_value_i32(i32 %0, i32* getelementptr inbounds ([1 x i32], [1 x i32]* @0, i32 0, i32 0), i32 1)
  ret i32 %2
}

declare i32 @__seahorn_get_value_i32(i32, i32*, i32)

define i32 @ValidateFunc() {
entry:
  %0 = load i32, i32* @3
  %1 = add i32 %0, 1
  store i32 %1, i32* @3
  %2 = call i32 @__seahorn_get_value_i32(i32 %0, i32* getelementptr inbounds ([1 x i32], [1 x i32]* @2, i32 0, i32 0), i32 1)
  ret i32 %2
}
```
which is the one I would expect.
Note I needed to define `addafter`. Maybe you forgot to do that?

**Comment by Robbin1987** [comment]
Hi Jorge, did you test with llvm 3.8? I used LLVM 3.6.

I reduced my code and forgot to put in the function for <addafter>.  I also tried your code, but I get a similar counter-example as with my previous code. result cex:

<
@0 = private constant [1 x i32] zeroinitializer
@1 = private global i32 0
@2 = private constant [1 x i32] zeroinitializer
@3 = private global i32 0
>

My current written code is based on LLVM 3.6 and had some problems with converting it to the MASTER.  Got issues with extracting debug information. The code part that I reused is currently commented in the MASTER. I will give it another try.

**Comment by caballa** [comment]
I'm using 3.8.

**Comment by Robbin1987** [comment]
I have taken the current master with llvm 3.8, but somehow the result keeps the same.

I use the following command: /sea pf -g -inline /media/sf_seahorn/sample/sample_f.c --cex=/media/sf_seahorn/sample/test.ll

What did you use?

`@0 = private constant [1 x i32] zeroinitializer
@1 = private global i32 0
@2 = private constant [1 x i32] zeroinitializer
@3 = private global i32 0'

it keeps on give me 'zeroinitializer', while you get the expected values.

Thanks in advance,

**Comment by Robbin1987** [comment]
Some addition information:

I work via Virtualbox and use shared folders to develop on Windows and build under Ubuntu. To create the framework and build environment I follow the steps mentioned within the travis build. This uses specific files, like: wget https://jorgenavas.github.io/sw/LLVM-3.8-Linux.tar.gz and wget https://jorgenavas.github.io/sw/Z3-Linux.tar.gz from you.

Could it be that these are not up-to-date anymore.

I noticed when I use the steps mentioned in the README, that I get errors (SQlite, IO error). This is caused because its working within shared folders and causes locking issues. I have now moved it outside the shared folder structure in Ubuntu and try the steps in the README again.

**Comment by agurfinkel** [comment]
@Robbin1987 , it is possible that the code is optimized to such a way that the counterexample is too hard to extract. Have you tried adding additional code (like an extra non-deterministic loop at the end) to extend the cex a bit.

**Comment by caballa** [comment]
If you add the flag `-O0` (i.e., disable optimizations) then you should get the expected harness.

**Comment by agurfinkel** [comment]
which is another way to make the cex longer ;)

**Comment by Robbin1987** [comment]
that did the trick (-O0). The default optimization was a bit too much. 

Thanks!
