### ISSUE TITLE
Extend sample code to have a good counter example

### ISSUE THREAD

**Issue by Robbin1987** [seahorn/seahorn#114]
Hi Guys,

I have troubles with creating sample code that generates a good and clear counter example. In my previous post we came to the conclusion that possibly the sample was to short to generate a good counter example, by disabling the optimizations we were able to get it correct.

I have tried several ways to increase the sample code, but none gave me a correct counter example with the optimizations enabled. With your experience, what would be a good extension to the following code snippet to get a good counter example?

my complete code as sample:

`extern int nd(void);
extern void __VERIFIER_error(void) __attribute__((noreturn));
#define assert(X) if(!(X)){__VERIFIER_error();}

extern int ValidateFunc(void);
extern int ValidateVal(void);
extern int nd ();
#define N 10
int a[N];

int addafter(int x, int y) {
  return x+y;
}

int display()
{

 int x=addafter(1,1); int y=3;
 if(ValidateFunc()==10) {
   int t1 = x;
   int t2 = y;
   x = t1+ t2;
   y = t1 + t2;
  }
   assert(y == 3);

   return 0;
}

int main() {
  if(ValidateVal())
  {
    display();
  }

  int i;
  for (i=0;i<N;i++)
  {
    if (nd ())
      a[i] = N;
  }

  return 0;
}`

with the current code I always get the following counter example:
`@0 = private constant [1 x i32] zeroinitializer
@1 = private global i32 0
@2 = private constant [1 x i32] zeroinitializer
@3 = private global i32 0`

Where the expected values are not there (zeroinitializer).

Since I am working on a visualization extension for SeaHorn it's easier to work with an optimized BMC trace than one that is not to start with.

Thanks in advance,

**Comment by caballa** [comment]
First note that the loop is dead code so LLVM will get rid of it.
More importantly, LLVM + SeaHorn preprocessing realize that if `ValidateFunc()` returns `10` the assertion will be definitely violated since it will know that `y = 5`. So in the end, it produces a single path. 
A simple fix is to replace `int y=3` at the beginning of the `Display` function with `int y = nd();`. 

This is the program I run:
```
extern int nd(void);
extern void __VERIFIER_error(void) __attribute__((noreturn));
#define assert(X) if(!(X)){__VERIFIER_error();}

extern int ValidateFunc(void);
extern int ValidateVal(void);
extern int nd (void);

#define N 10
int a[N];

int addafter(int x, int y) {
  return x+y;
}

int display()
{

  int x=addafter(1,1);
  //int y=3;
  int y = nd();
  if(ValidateFunc()==10) {
    int t1 = x;
    int t2 = y;
    x = t1 + t2;
    y = t1 + t2;
  }

  assert(y == 3);
  
  return 0;
}

int main() {
  if(ValidateVal()) {
    display();
  }

  int i;
  for (i=0;i<N;i++) {
    if (nd ()) {
      a[i] = N;
    }
  }
  return 0;
}
```

And these are the commands:

```
sea pf -m64 -O0 test_cex.2.c --inline --cex=test_cex.2.harness.ll 
sea exe -m64  test_cex.2.c  test_cex.2.harness.ll -o test_exe 
./test_exe
[sea] __VERIFIER_error was executed
```
