### ISSUE TITLE
seahorn_get_value ?

### ISSUE THREAD

**Issue by alx441** [seahorn/seahorn#121]
Hi Guys,
I watched an old example for seahorn at this address : 
https://asciinema.org/a/5jer5yp602ys6x885yl2674yw?autoplay=1%22 . 
Do you have an explanation on how I should proceed to get the line "seahorn_get_value" at run time ?
Thanks.

**Comment by caballa** [comment]
Can you elaborate more your question?

**Comment by alx441** [comment]
No problem.
For a program P, with one input, I try to understand how I can do, with seahorn, to get the input value (or a set of input values) that verifies an sassert condition in P .
 
It seems to me that in seahorn, we could extract this information with cex and log option (--cex=out.ll --log="cex") .

But if I understood correctly, the line "seahorn_get_value" , in the video, can prints value used at run time, who checks the label "__VERIFIER_error" obtained by the sassert condition.  

So my question is : "How can I do to obtain this information ?"

 If I misunderstood the functionality of "seahorn_get_value" , would you have an other solution ?

**Comment by caballa** [comment]
Right now, there is no other way that by looking at `seahorn_get_value` in the generated harness. However, you can look at lib/CexHarness.cc to see how from a model generated by the back-end solver we figure out how to assign a value to each input (e.g., external calls) of the program.

**Comment by alx441** [comment]
Thank you for the answer.
