### ISSUE TITLE
Inconsistent tests on Docker

### ISSUE THREAD

**Issue by mrthefakeperson** [seahorn/seahorn#123]
- `test-15-true.cpp` and `test-16-true.cpp` from the abc test folder can sometimes hang when run (time taken is >10 minutes)
 - Docker environment: trusty, pulled from docker hub using `docker pull seahorn/seahorn:trusty`, clang-3.8
 - to reproduce: run tests in the Docker container (under `/seahorn/build/run/share/seahorn/test`) using `lit abc`. Potentially adjust `lit.cfg` in the same directory to include these tests.

**Comment by caballa** [comment]
The same problem happened on my local ubuntu machine.
The temporary solution is to remove those benchmarks from the tests.
