### ISSUE TITLE
Soundness issues with conditionally terminating recursive programs

### ISSUE THREAD

**Issue by ezudheen** [seahorn/seahorn#132]
Hi,

I am getting some unsound verification results for the following programs.

#include "seahorn/seahorn.h"      // program-1
int __VERIFIER_nondet_int();
int special_idendity (int x) {
	if (x != 4) {
		x++;
		special_idendity (x);
	} else {
		return x;
	}
}
int main () { 
	int x = __VERIFIER_nondet_int();
	x = special_idendity (x);
	sassert(x == 4);
	return 0;
}  

int __VERIFIER_nondet_int();     // program-2
int special_idendity (int x) {
	if (x != 0) {
		special_idendity (!x);
	} else {
		return x;
	}
}
int main () { 
	int x = __VERIFIER_nondet_int();
	x = special_idendity (x);
	sassert(x == 0);
	return 0;
}

For both of the above programs, I expect UNSAT as the verification result, but the obtained result is SAT.
I also would like to know the techniques used for summary computation of the recursive programs.

Thanks
Ezudheen

**Comment by agurfinkel** [comment]
btw: recursive functions are not supported and are replaced by uninterpreted functions.

**Comment by ezudheen** [comment]
Can you please check the following program

extern int __VERIFIER_nondet_int(void);
int g;
int A(int a1, int a2) {   
	if (a1) {       
		A(a2,a1);   
	} else {       
		g = a2;
    	}
}

int main() {   
	int g = __VERIFIER_nondet_int();   
	int h = !g;   
	A(g,h);	
    	A(g,h);  
	sassert (g != 0);
	return 0;
}

**Comment by caballa** [comment]
I get `sat` here. If you expect `unsat` then the reason is explained above

**Comment by ezudheen** [comment]
OK, Thanks very much.

what will be the best way to fix this issue?

**Comment by agurfinkel** [comment]
Unfortunately, there is no best way. The underlying engine (`spacer`) supports recursive programs. However, vcgen in `seahorn` does not. Solving this requires changing vcgen in `seahorn`. This is not very difficult, but not trivial. There is documentation in the code with the steps required. We haven't had any cases of interesting recursive programs to verify and decided not to support this at the moment. Other features, such as cex generation also don't support recursive functions and would have to be fixed. There is no easy work-around.

**Comment by agurfinkel** [comment]
Currently, the recursive call to `special_identity()` is treated as an uninterpreted function, and the expected result of verification is `sat`. `SeaHorn` should print a warning alerting you that it is unsound due to recursion.

**Comment by ezudheen** [comment]
Hi,

Are the datatypes used inside Seahorn are bounded or unbounded? for the following programs if the datatypes are unbounded then the expected result is UNSAT but the obtained result is SAT. 

int special_idendity (int x) { // Pgm-2
	int flag = x*x;
	if (flag > 0) {
		x--;
		return special_idendity (x);
	} else {
		return x;
	}
}
int main () {    
	int x = __VERIFIER_nondet_int();
	x = special_idendity (x);
	sassert(x == 0);
	return 0;
}

int special_idendity (int x) {  // Pgm-2
	int flag = (x*x)*x;
	if (flag <= 0) {
		x--;
		return special_idendity (x);
	} else {
		return x;
	}
}
int main () { 
	int x = __VERIFIER_nondet_int();
	x = special_idendity (x);
	sassert(x > 0);
	return 0;
}

**Comment by caballa** [comment]
When seahorn synthesizes invariants using spacer it reasons about mathematical integers. But seahorn can also use a BMC engine over bitvectors which it's sound wrt machine arithmetic. I think here the problem is that there are non-linear constraints. For that we rely on Z3 which is not very reliable for that.
