### ISSUE TITLE
Cannot install seahorn due to errors

### ISSUE THREAD

**Issue by thiago-cavalcante** [seahorn/seahorn#133]
Hi,

I followed your tutorial at https://github.com/seahorn to install it but always encounter an issue at the command: `cmake -DCMAKE_INSTALL_PREFIX=run ../`
In brief, the error is: error: `-- Configuring incomplete, errors occurred!` Below is the detailed log:
```
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
-- Could NOT find Z3 (missing:  Z3_LIBRARY Z3_INCLUDE_DIR Z3_EXECUTABLE) (Required is at least version "4.3.2")
CMake Warning at CMakeLists.txt:121 (message):
  No Z3 found.  Run

  	cmake --build .  && cmake /home/svlab/repos/seahorn


-- Found LLVM 3.8.0
-- Using LLVMConfig.cmake in: /home/svlab/repos/seahorn/build/run/share/llvm/cmake
-- Building with -fPIC
arch: x86_64
-- All crabllvm libraries will be built statically
CMake Warning at crab-llvm/CMakeLists.txt:146 (message):
  No crab found.  Run

  	cmake --build .  --target crab && cmake /home/svlab/repos/seahorn


-- Compiling sea-dsa without sanity checks
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
Z3_LIBRARY (ADVANCED)
    linked by target "seahorn" in directory /home/svlab/repos/seahorn/tools/seahorn
    linked by target "seapp" in directory /home/svlab/repos/seahorn/tools/seapp
    linked by target "units_z3" in directory /home/svlab/repos/seahorn/units

-- Configuring incomplete, errors occurred!
See also "/home/svlab/repos/seahorn/build/CMakeFiles/CMakeOutput.log".
```
I already have installed Z3 separetely.
Could you advise whether I do something incorrectly?

Thanks in advance!

**Comment by caballa** [comment]
Have you tried to run `cmake --build .  && cmake /home/svlab/repos/seahorn`. That command will keep going with the installation process and it will try to install Z3, etc. 
Note that you say that you have installed Z3 but `cmake` cannot find it. If you want it to find it you need to pass the option `--Z3_ROOT=....`. Having said that, here `Z3` means actually spacer (https://bitbucket.org/spacer/code) which is the back-end solver SeaHorn uses and it's built on the top of Z3. 

Having said all of this, `cmake` shouldn't finish with an error. Could you send us `/home/svlab/repos/seahorn/build/CMakeFiles/CMakeOutput.log` for more details.

**Comment by agurfinkel** [comment]
Please use our docker build, or follow the instructions to build in docker:
http://seahorn.github.io/seahorn/install/docker/2018/02/24/seahorn-with-docker.html

SeaHorn requires specific versions of its dependencies. Just because you have other versions of the tools installed will not work. Having them installed might confuse the build system. 

The best way to go is to compile everything in a dedicated environment provided by Docker. We provide both the necessary docker files and nightly docker build.

**Comment by thiago-cavalcante** [comment]
@caballa   yes, I already tried that but the error still.
