### ISSUE TITLE
Confusion between `-o` and `--oll` in sea pf command

### ISSUE THREAD

**Issue by caballa** [seahorn/seahorn#137]
`sea pf` accepts `-o file.smt2` and `--oll=file.ll` among many other options.

The confusion is when users write `-oll=file.ll` which is parsed as `-o ll=file.ll` and therefore, it creates a file called `ll=file.ll` in smt2 format rather than `.ll` as intended.

Another issue is the output of `sea pf --help`:

`--oll ASM_OUT_FILE    LLVM assembly output file`

Therefore, the user might try `--oll test.ll`  which is parsed as `-o ll test.ll` 

A simple solution is to rename `oll` so that the first letter is not `o`.

**Comment by agurfinkel** [comment]
Are you sure about this problem. Can you create a repro?

I often miss the double `-`, but I don't recall command interpreted as smt output file.

The second use case does not sound believable. The command line parser does not distinguish between `--opt=value` and `--opt value` and never decides to parse long option `--` as a short option `-`

**Comment by caballa** [comment]
I'm surprised. These issues have been there forever.

Try `sea pf tests/simple/01_unsat.c --oll test.ll`
You should see `error: Bitcode was not properly read; Could not open input file: No such file or directory`

Try `sea pf tests/simple/01_unsat.c -oll=test.ll`
You will see the file `ll=test.ll` which contains the verification conditions in smt2.file.

The correct command is only `sea pf tests/simple/01_unsat.c --oll=test.ll`

**Comment by caballa** [comment]
With the first command we get at least an error but it's hard to see what is going on if you are new.

**Comment by caballa** [comment]
Never further investigated so we close it for now.
