### ISSUE TITLE
Is it expected that some samples under folder `play` have incorrect verification result or cannot terminate?

### ISSUE THREAD

**Issue by rdzhou** [seahorn/seahorn#143]
Thank you for your great work. I wonder if seahorn can correctly handle all the samples under the folder `play`. I tried the following samples inside the latest seahorn docker image and found that some samples have incorrect results or cannot terminate. Is this the expected result?

incorrect result: 
sea pf seahorn/play/arrays/test00.c   (sat, should be unsat)

cannot terminate:
sea pf seahorn/play/arrays/test02.c
sea pf seahorn/play/arrays/test03.c
sea pf seahorn/play/arrays/test04.c
sea pf seahorn/play/arrays/test06.c

**Comment by agurfinkel** [comment]
Yes. Files in `play` directory are various examples that we are "playing" with. These are usually instances that are hard to solve, require special options, used to be solved by some prior technique, appeared somewhere we found interesting, and things we would like to be able to solve in the future.

**Comment by rdzhou** [comment]
I see. Thank you very much for your prompt reply!
