### ISSUE TITLE
Does seahorn support loop summarization?

### ISSUE THREAD

**Issue by DanielGuoVT** [seahorn/seahorn#146]
Hi,
A quick question: does Seahorn support some kind of loop summarizations?

Thanks,
Daniel.

**Comment by agurfinkel** [comment]
SeaHorn verifies safety properties (i.e., assertions) of programs. For a program with a loop, when successfully verified, SeaHorn will produce a loop invariant summarizing behavior of the loop. SeaHorn will also produce function summaries if necessary.
