### ISSUE TITLE
The counter example issues

### ISSUE THREAD

**Issue by qian-feng** [seahorn/seahorn#149]
Hi, I tried to use horn-cex to generate the counter example, but i do not know how to read it. It seems to be a snippet of LLVM bitcode, could you tell me how i map them back to the source code? How can I locate the bug in the code?  I really appreciate your help, thanks！

Best,

**Comment by caballa** [comment]
Did you read http://seahorn.github.io/seahorn/cex/validation/2016/10/16/cex-validation.html ?

**Comment by qian-feng** [comment]
Thanks！It seems that seahorn only generates the part of llvm bitcode. Is there way we can obtain the mapping between the cex and the original source code. Without the mapping, it is hard to find the location and condition which triggered the bug. Thanks a lot.

**Comment by caballa** [comment]
If you run `sea` with option `-g` and then add the option `--log=cex` you should see that map

**Comment by agurfinkel** [comment]
The intention is that seahorn gives you everything that you need to debug your code in your usual way and use your usual tools (debugger, debug print statements, etc.) to identify how compiled code corresponds to the original source.
