### ISSUE TITLE
the memory safety check

### ISSUE THREAD

**Issue by qian-feng** [seahorn/seahorn#151]
Hi, I am trying to use Seahorn to conduct the memory safety check, but it always show "no assertion". Does seahorn support "Malloc" operation? Why do I see the undefined call in the final bc? The example is as following: 
```
''#include "seahorn/seahorn.h"
#include <stdlib.h>
struct my{
  char* x;
  int y;
};
int main(void){
  struct my *t = malloc(sizeof(struct my));
  t->x = malloc(10*sizeof(char));
  t->x="123";
  t->y=1;
  free(t);
  return 1;
}
```

**Comment by caballa** [comment]
I'm assuming you are trying something like `sea abc test.c`.  LLVM is smart enough to realize that the malloc and all the initialization code is dead code so it converts main into:

``` 
int main(void) {
       return 1;
}
```
I tried with the flag -O0 to disable LLVM optimizations as much as possible but it stills removes all the code. 

If you add the `volatile` attribute to the first line in main then LLVM won't remove the code.
However, in this case the instrumentation pass in SeaHorn will see that all the accesses are trivially in-bounds so it won't add any assertion.

**Comment by caballa** [comment]
You can, however, this this example
```
#include "seahorn/seahorn.h"
#include <stdlib.h>

extern int nondet_int(void);
extern void process_char(char);

struct my{
char* x;
int y;
};

int main(void){
  volatile struct my* t = (struct my*) malloc(sizeof(struct my));
  t->x = malloc(10 * sizeof(char));
  t->x="123";
  t->y=1;

  int i = nondet_int();
  assume(i >=0 && i <= 2);
  process_char(t->x[i]);
  
  free(t);
  return 1;
}
```

And SeaHorn will add assertions. The key difference here is that we add symbolic accesses (through `i`) that the instrumentation cannot reason about it. So it will add assertions that will be proven by SeaHorn back-end solvers.

**Comment by qian-feng** [comment]
Thanks. However, in this example, it has the memory safety issue. t could be null, since malloc result could be null pointer. In this case, does it mean seahorn will miss this check? Thanks.

**Comment by kuhar** [comment]
Currently, allocations are assumed to always return you fresh memory and OOM errors are not checked.

**Comment by caballa** [comment]
Also, the option `sea abc` does not  check whether a pointer is null or not. We have a separate pass that adds checks for null dereferences so it should check that what `malloc` returns is not null.

**Comment by qian-feng** [comment]
Hi, if possible, could i know the name  of that pass? Thanks a lot.

Best

**Comment by caballa** [comment]
The command is `sea ndc`.
It has never been tested beyond small programs but it seems to work with your example.

**Comment by qian-feng** [comment]
Hi, I am trying to use Seahorn to conduct the memory check on Rpython backend C programs. I basically use sea abc to conduct the check. However, it always shows 'sat' for the following case:
```
#include "common_header.h"
#include "structdef.h"
#include "forwarddecl.h"
#include "preimpl.h"
#include <src/rtyper.h>

#include <stdlib.h>
#include <string.h>
#include "seahorn/seahorn.h"
static struct _RPyString_dump_t {
        struct _RPyString_dump_t *next;
        char data[1];
} *_RPyString_dump = NULL;

char *RPyString_AsCharP(RPyString *rps)
{
        Signed len = RPyString_Size(rps);
        struct _RPyString_dump_t *dump = \
                        malloc(sizeof(struct _RPyString_dump_t) + len);
        if (!dump)
                return "(out of memory!)";
        dump->next = _RPyString_dump;
        _RPyString_dump = dump;
        memcpy(dump->data, rps->rs_chars.items, len);
        dump->data[len] = 0;
        return dump->data;
}

void RPyString_FreeCache(void)
{
        while (_RPyString_dump) {
                struct _RPyString_dump_t *dump = _RPyString_dump;
                _RPyString_dump = dump->next;
                free(dump);
        }
}

int main(){
  //RPyString_FreeCache();
  RPyString *rps = malloc(sizeof(RPyString) + 15);
  if(rps==NULL) return 0;
  memset(rps, 0, sizeof(RPyString));
  RPyString_AsCharP(rps);
  printf("%d", 0);
  free(rps);
}

```
However, it has been verified by smack and shows ``no error'' for it. Could you tell me why it happens like this. It seems that I have already conduct the pointer check at any possible pointer check and the program seems there is no bug in it. Thanks a lot.

**Comment by caballa** [comment]
It's hard to see what is happening without running SeaHorn by myself.
I cannot compile it because the first 5 header files are missing. 
Can you send a tarball with all the files and the exact command you are trying?

**Comment by qian-feng** [comment]
Hi, thanks for your help. The header files are in the attachment. Thanks.
Best,
Qian



[header.zip](https://github.com/seahorn/seahorn/files/2106963/header.zip)

**Comment by qian-feng** [comment]
Hi, i used the command is "sea abc rtyper.o.bc".  Thanks.

**Comment by caballa** [comment]
I cannot compile your program even with the files you sent.
I get errors like this:
```
./common_header.h:92:10: fatal error: 'sys/mman.h' file not found
#include <sys/mman.h>
         ^
```
`common_header .h` is full of header files that cannot be found either in Mac or Linux.
You must be adding these header files somehow. 

Anyway, you can also send me the bitcode generate by SeaHorn before the instrumentation.

**Comment by qian-feng** [comment]
Hi Jorge, I sent the bc file to you via gitter. Thanks.

Best,
