### ISSUE TITLE
Is this is a bug?

### ISSUE THREAD

**Issue by chkl** [seahorn/seahorn#152]
Hi,
I'm having trouble with a simple c file that `seahorn` won't verify for me.
Consider this file (`assert_false.c`):
```c
extern void __VERIFIER_error() __attribute__((__noreturn__));
void __VERIFIER_assert(int cond)
{
    if (!cond)
    {
    ERROR:
        __VERIFIER_error();
    }
}
extern int __VERIFIER_nondet_int();
int main()
{
    int a[3];
    int e = __VERIFIER_nondet_int();
    int i = 0;
    while (i < 3 && a[i] != e)
    {
        __VERIFIER_assert(0);
        i = i + 1;
    }
    return 0;
}
```
Running `./sea pf assert_false.`  results in the output:
```
 > ./sea pf assert_false.c 
/usr/bin/clang-3.8 -c -emit-llvm -D__SEAHORN__ -fgnu89-inline -m32 -Iinclude -o /tmp/sea-0Sos77/assert_false.bc assert_false.c
/verifiers/seahorn/bin/seapp -o /tmp/sea-0Sos77/assert_false.pp.bc --strip-extern=false --promote-assumptions=false --kill-vaarg=true /tmp/sea-0Sos77/assert_false.bc
/verifiers/seahorn/bin/seapp -o /tmp/sea-0Sos77/assert_false.pp.ms.bc --horn-mixed-sem --ms-reduce-main /tmp/sea-0Sos77/assert_false.pp.bc
/verifiers/seahorn/bin/seaopt -f -funit-at-a-time -o /tmp/sea-0Sos77/assert_false.pp.ms.o.bc -O3 --enable-indvar=false --enable-loop-idiom=false --enable-nondet-init=false --unroll-threshold=150 --disable-loop-vectorization=true --disable-slp-vectorization=true --vectorize-slp-aggressive=false /tmp/sea-0Sos77/assert_false.pp.ms.bc
/verifiers/seahorn/bin/seahorn --keep-shadows=true --horn-solve -horn-inter-proc -horn-sem-lvl=mem --horn-step=large /tmp/sea-0Sos77/assert_false.pp.ms.o.bc
unsat

```
which is slightly surprising.

**Comment by agurfinkel** [comment]
`a[3]` is uninitialized, so `a[i] != e` is undefined. Any behaviour is correct.

BTW: it is better to use `#include <seahorn/seahorn.h>` for the definitions of `assert/error/assume`

**Comment by chkl** [comment]
Thank you for your response. Shouldn't an uninitialized variable be indeterminate? In that case, `a[i]` *could* be `e`. It just feels slightly odd that a verifier would say that the program cannot reach an error state when in the most common C implementations (clang,gcc) it factually can reach it.

**Comment by agurfinkel** [comment]
According to C standard, accessing uninitialized variables is an undefined behaviour. I expect both clang and gcc to compile the program into a noop (when the program is sliced to only include the paths to assertion and optimized with `O3`). In general, it is not a good idea to rely on any specific interpretation of undefined behaviour. In SeaHorn, we use clang and llvm to pre-process the program. Both of these tools apply different heuristics to deal with undefined behaviour. The result is completely unpredictable.

**Comment by chkl** [comment]
I see, thank you for the explanation.

**Comment by caballa** [comment]
The array is uninitialized so llvm decides to remove some code due
to.undefined behavior
