### ISSUE TITLE
Working with multi-file project

### ISSUE THREAD

**Issue by sayakray** [seahorn/seahorn#153]
Is there any tutorial/instruction available to work on multi-file project? My project is written in C, but distributed over multiple files with include files distributed over multiple locations. Assertions are distributed too.

**Comment by caballa** [comment]
If you can easily generate llvm bitcode for each file then you can just pass all the *.bc files to the command `sea pf`. This command will simply call `llvm-link` to generate a single *.bc file.

If the project uses makefiles to generate a final executable then you can use `gllvm` (https://github.com/SRI-CSL/gllvm) to generate a single bitcode file that then you can feed to `sea pf`

**Comment by sayakray** [comment]
Thank you Jorge! As I would like to avoid bringing another tool in our solution to support multi-file projects, the first approach (use of llvm-link) sounds more reasonable to me. However, I experienced the following issues as I worked with seahorn in the docker environment:
1. I created .bc files from the source .c files separately. When I called "sea pf" on the generated .bc files, I received the error message "error: Bitcode was not properly read; Could not open input file: No such file or directory"
2. Upon failing on the step 1 above, I used llvm-link (llvm-link-3.8 for my case) explicitly to stitch my .bc files into a new .bc  file. When I called "sea pf" on this new .bc file, seahorn did finish its run and reported "sat" (I was indeed expecting a cex).  Now, how do I suppose to use the generated .ll test harness to construct the error run? I tried "sea exe" to generate the error run (I followed what is explained in  http://seahorn.github.io/seahorn/cex/validation/2016/10/16/cex-validation.html, only replaced the single .c file mentioned in the example with the set of .c files that I have). An executable file is generated. However, once I ran the executable, I got  "exiting with a call to __assert_fail". When I ran lldb on that executable, it was also terminated with the same __assert_fail message.

**Comment by caballa** [comment]
The `__assert_fail` indicates something went wrong during the  generation of the executable cex. We have been improving the implementation of cex generation but it's on the `dev` branch since we are still working on it. 

Is it possible for you to give us the .c files together with the commands you use to generate the bc files? I could try  and see what happens with the newest implementation.

**Comment by sayakray** [comment]
I have attached a zipped folder that contains the following:

1. a toy program that comprises of two files, viz. 3_test.c and read_a.c. 3_test.c has the main function which calls a function defined in read_a.c. The objective is to generate a counterexample that shows violation of the assertion at line 15 of 3_test.c. For example, when b is a negative integer, I am expecting the assertion to fail. 
2.  3_test.bc and read_a.bc - these files are generated using clang-3.8 using the following commands:
clang-3.8 -S -emit-llvm -I../../seahorn/seahorn/include/ 3_test.c -o 3_test.bc
clang-3.8 -S -emit-llvm -I../../seahorn/seahorn/include/ read_a.c -o read_a.bc

However, when seahorn is run on these two bc files, I got the following error message:

usea@a5be9344df7a:/opt/seahorn$ sea pf --cex=/host/witness.ll /host/3_test.bc /host/read_a.bc
/opt/seahorn/bin/seapp -o /tmp/sea-q76ClE/merged.pp.bc --strip-extern=false --promote-assumptions=false --kill-vaarg=true /tmp/sea-q76ClE/merged.bc
error: Bitcode was not properly read; Could not open input file: No such file or directory

3. 3_test_comb.bc - this file is generated by llvm-link using the following command:
llvm-link-3.8 3_test.bc read_a.bc -o 3_test_comb.bc

4. witness.ll - this file is generated by seahorn once it successfully runs on 3_test_comb.bc. The command I used is the following:
sea pf --cex=/host/witness.ll /host/3_test_comb.bc

5. 3_test_debug - this executable file is generated as I ran the following command (here I am directly referring to the C files 3_test.c and read_a.c directly - is this the right way?)
sea exe -m64 -g /host/3_test.c /host/read_a.c /host/witness.ll -o 3_test_debug

However, as I am trying to execute this file, I am getting the error message:
[sea] exiting with a call to __assert_fail

Hope this explains my situation. Please let me know if you need any further information/clarification.

[code.zip](https://github.com/seahorn/seahorn/files/2198786/code.zip)

**Comment by caballa** [comment]
Thanks for all the detailed information.
The reason is a known problem in the way the back-end solver generates cex for trivial cases. 
We will release soon a new version of the solver that will generate properly cex's in these cases. We have made a temporary fix to cover your case.

I've tried with these two commands and it seems to work:

```
sea pf 3_test.c read_a.c  --cex=harness.ll 
sea exe -m64  3_test.c read_a.c harness.ll -o test.exe
```

**Comment by sayakray** [comment]
Is the chang pushed in the docker distribution? I am getting the same error there as before.

**Comment by caballa** [comment]
The docker distribution is supposed to be updated nightly.
I'll try to see what is going on.

**Comment by agurfinkel** [comment]
`nightly` is updated every day. As of now, the last update is 18 hours ago. Note that you need to specifically pull the `nightly` tag. https://hub.docker.com/r/seahorn/seahorn/tags/
