### ISSUE TITLE
Completeness issue

### ISSUE THREAD

**Issue by chkl** [seahorn/seahorn#157]
Hi,

we found the following program that shows some odd behavior of seahorn:
```c
extern void __VERIFIER_error() __attribute__((__noreturn__));
extern unsigned int __VERIFIER_nondet_uint(void);
void __VERIFIER_assert(int cond)
{
    if (!cond)
    {
    ERROR:
        __VERIFIER_error();
    }
    return;
}
unsigned int mp_add(unsigned int a, unsigned int b)
{
    unsigned char  a1;
    unsigned char b1, b2;
    unsigned short carry;
    unsigned short partial_sum;

    a1 = a >> 8;

    // a1 = 81;
    __VERIFIER_assert(a1 == 81);

    b1 = b >> 8u;
    b2 = b >> 16u;
 
    printf("b1 = %d", b1);

    carry = 0;
    int i = 0;
    while (i < 1 || carry != 0) {
        __VERIFIER_assert(i == 2 || carry + a1 + b1 != 0);
        partial_sum = carry;
        carry = 0;
        
        if ( i == 2) {
		partial_sum += 256;
        }
        if (partial_sum > 255) {
            partial_sum = partial_sum & 255;
            carry = 1;
        }
	i++;
    }
    return 0;
}
int main()
{
    unsigned int b = __VERIFIER_nondet_uint();
    return mp_add(234770789, b);
}
```
At the location of the assignment `a1 = 81`, the value of a1 is already 81. As can be verified with the assertion `__VERIFIER_assert(a1 == 81)` (e.g. verifying the program without the assertion and with only the first assert results in "unsat"). 

Verifying the program without the assignment results in the verdict "sat", but with the assignment it is "unsat". This incompleteness is a little surprising.

Is this a bug, or is this some optimization artifact?

Thank you,
Chris

**Comment by agurfinkel** [comment]
What version of SeaHorn are you using and with what options?
I can see that there is a lot of bit-vector manipulation in this example.
Currently, SeaHorn abstracts such operations as non-deterministic, except during bit-precise BMC. 
If you are not using bmc mode, this would be the source of the issue.

**Comment by chkl** [comment]
I'm using seahorn built from commit 9c4a917a595e11d673eed216701df106b73fdbda. The imprecision does not seem to be related to the bitwise operations. Here's a modified example that does not use any of those.

```c
extern void __VERIFIER_error() __attribute__((__noreturn__));
extern unsigned int __VERIFIER_nondet_uint(void);
extern unsigned char __VERIFIER_nondet_uchar(void);
void __VERIFIER_assert(int cond)
{
    if (!cond)
    {
    ERROR:
        __VERIFIER_error();
    }
    return;
}
unsigned int mp_add(unsigned int a, unsigned int b)
{
    unsigned char  a1;
    unsigned char b1;
    unsigned short carry;
    unsigned short partial_sum;
    a1 = __VERIFIER_nondet_uchar();
    if (a1 != 81) {
        return 0;
    }
    b1 = __VERIFIER_nondet_uchar();

    carry = 0;
    int i = 0;
    while (i < 1 || carry != 0) {
        __VERIFIER_assert(i == 2 || carry + a1 + b1 != 0);
        partial_sum = carry;
        carry = 0;

        if ( i == 2) {
        partial_sum += 256;
        }
        if (partial_sum > 255) {
            partial_sum = partial_sum & 255;
            carry = 1;
        }
    i++;
    }
    return 0;
}
int main()
{
    unsigned int b = __VERIFIER_nondet_uint();
    return mp_add(234770789, b);
}
```
seahorn without `--bmc` still returns `sat`.

The assertion should quite trivially hold (`carry` is always 0 or 1, `a1` is 81 after line 20 and b1 is an unsigned char, therefore `carry + a1 + b1` should be non-zero).

**Comment by agurfinkel** [comment]
In the regular mode, i.e., `sea pf`, all numeric types are abstracted into arbitrary precision signed integers. In particular, there is no difference between `char`, `short`, `int`, and `unsigned`. Bit operations, like `partial_sum = partial_sum & 255` are replaced by non-deterministic assignments. Overflow is not modeled. 

This abstraction has worked well for verifying properties that do not depend on the difference between machine and mathematical representation on integers. 

SeaHorn does support more precise modeling of integer operations, but only in BMC mode (i.e., on programs with no loops and inlined functions). 

We are very interested in extending support for bit-precise arithmetic in `sea pf` mode, but this is still at experimenal / planning stages.

**Comment by chkl** [comment]
I just replaced the `partial_sum = partial_sum & 255` with `partial_sum = 0`. The problem is not related to the bitwise functions. Somehow the `if (a1 != 81) { return 0; }` does not cause an "`assume  (a1 = 81)`" for the continuing code path. E.g. if I add an assignment `a1 = 81;` after the if, then seahorn says "unsat" otherwise it says "sat".

**Comment by chkl** [comment]
Oh, I see. Thank you very much for the clarification.
