### ISSUE TITLE
Port to llvm 5.0

### ISSUE THREAD

**Issue by caballa** [seahorn/seahorn#162]
Tasks to be done: 
- [x] Port llvm-seahorn to LLVM 5.0
- [x] Port sea-dsa to LLVM 5.0
- [x] Port llvm-dsa to LLVM 5.0
- [x] Port crab-llvm  to LLVM 5.0
- [ ] Pass all tests

All these tests passed OK:
- test-simple
- test-solve
- test-abc
- test-dsa
- test-formats
- test-bmc

Tests that fail but in the same way that `deep-dev` (3.8) branch:
 - pred-abs  (6 of them)
 - test-smc   (only 1 of them)

**New FAILED tests**:
    
 - test-tutorial       

    In `deep-dev` (llvm 3.8) branch the following tests failed:

      - `ssft_simple_8.c` 
      - `ssft_simple_9.c` 

    In `deep-dev-5.0` (llvm 5.0) the following tests fail:

      - **`ssft_simple_2.c`**
      - **`ssft_simple_6.c`**
      - `ssft_simple_9.c`

 Of special interest is `ssft_simple_2.c` because the command:

`sea pf -O3 ../test/tutorial/ssft_simple_2.c --max-depth=9`

does not terminate even if we fix a maximum depth search. 

In case you wonder, the command:

`sea pf -O0 ../test/tutorial/ssft_simple_2.c --max-depth=9`

does terminate. 

- [x] Update travis

**Comment by agurfinkel** [comment]
in travis build, `tutorial/lock.c` is failing as well. Something to do with counterexamples.
