### ISSUE TITLE
Compile seahorn locally

### ISSUE THREAD

**Issue by tregua87** [seahorn/seahorn#170]
I am trying to compile seahorn from the repo.

After running:

`cmake -DCMAKE_INSTALL_PREFIX=run ../`

I got:
```
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   system
-- Could NOT find Z3 (missing: Z3_LIBRARY Z3_INCLUDE_DIR Z3_EXECUTABLE) (Required is at least version "4.3.2")
CMake Warning at CMakeLists.txt:121 (message):
  No Z3 found.  Run

  	cmake --build .  && cmake .../seahorn


-- Could NOT find LLVM (missing: LLVM_DIR)
CMake Warning at CMakeLists.txt:158 (message):
  No llvm found.  Run

  	cmake --build .  && cmake .../seahorn


-- Configuring done
-- Generating done
-- Build files have been written to: .../seahorn/build
```

The problem is that I have already installad LLVM and I would say to seahorse "Hi! LLVM is here...".

How can I do that? :) 

Thanks.

**Comment by agurfinkel** [comment]
SeaHorn relies on custom compilation flags for LLVM (e.g., enable exceptions and RTTI). Compiling against other versions of LLVM is not recommended. If you really want to use a pre-compiled version of LLVM, and you got one of our pre-compiled LLVM binary distributions, you can find the appropriate options by looking through our docker build scripts here: https://github.com/seahorn/seahorn/tree/master/docker
