### ISSUE TITLE
Test fail in deep-dev-5.0

### ISSUE THREAD

**Issue by agurfinkel** [seahorn/seahorn#173]
Some tests are failing in `deep-dev-5.0`. I believe they were passing in `deep-dev`. This might be llvm5.0 related. See details in commit:  f071551

`lock.c` complains about not being able to find sufficiently long counterexample
`ssft_simple_6.c` does not converge under many different options (but converges under some)
`ssft_simple_9.c` takes too long even with a small depth bound of 9

**Comment by caballa** [comment]
Yes, I noticed some of them here https://github.com/seahorn/seahorn/issues/162

**Comment by agurfinkel** [comment]
Duplicate of issue #162
