### ISSUE TITLE
Properly update function aliastes

### ISSUE THREAD

**Issue by kuhar** [seahorn/seahorn#186]
We don't properly update functions aliases in:
- externalizeAddressTakenFunctions
- KillVarArgFuncs
- potentially other functions that replace / delete functions

Repro:
```
git clone https://github.com/seahorn/seahorn -b brunch
build everything
cd  kuhar/points-to-bitcode/5.0/CASS
SEAHORN_DIR=your_dir/run/bin ../run.sh CASS.llvm5.externalized.o0.g.bc true
```

**Comment by caballa** [comment]
Fix here bb8b602c82ff3540d0b2e4df773df053b7980de0
