### ISSUE TITLE
Failure after switch lowering

### ISSUE THREAD

**Issue by kuhar** [seahorn/seahorn#187]
Seapp runs into a verification error on llvm-dis:
`PHINode should have one entry for each predecessor of its parent basic block!`
just after the LowerSwitch pass.
It's not clear if it's a bug in llvm or on our side.

Repro:
```
git clone https://github.com/seahorn/seahorn -b brunch
build everything
cd  kuhar/points-to-bitcode/5.0
unpack https://github.com/kuhar/points-to-bitcode/releases into the clang subdirectory
modify run.sh and set `--kill-vaarg=false`, `--externalize-addr-taken-funcs=false`
cd clang
SEAHORN_DIR=your_dir/run/bin ../run.sh llvm-dis.bc true
```

**Comment by agurfinkel** [comment]
This is caused by `llvm::LowerSwitch`. Happens even if that is the only pass ran.
There are bug fixes to this pass in `LLVM 7.0`. We can try and back-port them.
Unfortunately they are intermixed with user C++ and LLVM related cleanups
