### ISSUE TITLE
Building issues

### ISSUE THREAD

**Issue by mchalupa** [seahorn/seahorn#189]
Hi,

when I follow the building instructions from the README, I'm getting this error:

```
[ 23%] Performing install step for 'llvm'
CMake Error at /home/marek/src/seahorn/build/llvm-prefix/src/llvm-stamp/llvm-install-RelWithDebInfo.cmake:16 (message):
  Command failed: 2

   '/usr/bin/make' 'install'

  See also

    /home/marek/src/seahorn/build/llvm-prefix/src/llvm-stamp/llvm-install-*.log


make[2]: *** [CMakeFiles/llvm.dir/build.make:75: llvm-prefix/src/llvm-stamp/llvm-install] Error 1
make[1]: *** [CMakeFiles/Makefile2:265: CMakeFiles/llvm.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

The referenced file contains:

```
  1 CMake Error at cmake_install.cmake:41 (file):
  2   file INSTALL cannot make directory "/usr/local/include/llvm": Permission
  3   denied
  4 
  5 
  6 make[3]: *** [Makefile:86: install] Error 1
```

so it looks like the install prefix is not set correctly for LLVM.

**Comment by caballa** [comment]
This is the default install directory chosen by cmake. Either you do `sudo make install` or you just give a different install directory `cmake -DCMAKE_INSTALL_PREFIX=some_local_directory ...`. I always do the latter.

**Comment by mchalupa** [comment]
I see. I would just expect that this is automated, as I am supposed to use `-DCMAKE_INSTALL_PREFIX=run` when configuring the project and the README also says that: "The install target installs SeaHorn all of it _dependencies_ under `build/run`"

**Comment by mchalupa** [comment]
By automated I meant that the `CMAKE_INSTALL_PREFIX` would be propagated into the LLVM build.

**Comment by agurfinkel** [comment]
@mchalupa , can you let me know your exact cmake / make commands and build environment. 
`CMAKE_INSTALL_PREFIX` is propagated to LLVM: https://github.com/seahorn/seahorn/blob/master/CMakeLists.txt#L137

So this might be something specific to your configuration. 

The easiest way to build seahorn in an unexpected environment is to use docker.
You can get the latest binary from docker hub using 
```
docker pull seahorn/seahorn-llvm5:nightly
```

You can also get only a build container. Complete build instructions for docker are here:
https://github.com/seahorn/seahorn/blob/deep-dev-5.0/docker/seahorn-full-size-rel.Dockerfile

**Comment by mchalupa** [comment]
@agurfinkel, I'm using Arch Linux (64 bit) and I precisely followed the steps from the README:

```
cd seahorn ; mkdir build ; cd build
cmake -DCMAKE_INSTALL_PREFIX=run ..
cmake --build .
```
