### ISSUE TITLE
LLVM bitcode generated using new Clang on OSX not recognized

### ISSUE THREAD

**Issue by wky** [seahorn/seahorn#19]
I'm on OSX 10.11.4, Xcode 7.3 with Clang:

> Apple LLVM version 7.3.0 (clang-703.0.29)

seapp, llvm-dis and other tools built within seahorn cannot recognize any bit code files generated by the above Clang, giving errors like this:

> error: Invalid type for value

The error occurred somewhere in function `BitcodeReader::ParseConstants()` in file `ext/llvm/lib/Bitcode/Reader/BitcodeReader.cpp`

Is this a compatibility issue with the old LLVM seahorn is using now?

Clang-3.6 on Ubuntu had no issue.

**Comment by caballa** [comment]
As a general rule, SeaHorn works with llvm 3.6. 
The Clang version should be the same.

**Comment by wky** [comment]
I have no idea how Apple shipped Clang versions maps to LLVM.org versions, so I'm installing a new set of LLVM tools by hand. Which version should I get, 3.6.0, 3.6.1 or 3.6.2? (from http://llvm.org/releases/download.html)

**Comment by caballa** [comment]
You need to get Clang 3.6.0. 
SeaHorn will download automatically llvm 3.6.0.  

If you want to use LLVM utilities (llvm-dis, llvm-as,etc) then you can either use the binaries from seahorn/build/run/bin  or install by yourself llvm 3.6.0. 

I wouldn't bother installing llvm 3.6.0. I usually use the binaries from build/run/bin.

**Comment by wky** [comment]
Thank you. I have resolve my problem.
