### ISSUE TITLE
[llvm-5.0] false positive with --enable-loop-idiom

### ISSUE THREAD

**Issue by mchalupa** [seahorn/seahorn#191]
Hi,

I'm using seahorn from the nightly builds (version `0.1.0-rc3-5bcd7c9`).
If I run it with `--enable-loop-idiom` on this program:  https://github.com/sosy-lab/sv-benchmarks/blob/master/c/loop-lit/mcmillan2006.c, I get that there is an error. I used this command:

```
sea  pf --horn-stats --enable-loop-idiom  /var/tmp/sv-benchmarks/c/loop-lit/mcmillan2006.c
```

If I omit `--enable-loop-idiom`, then the answer changes. Works the same also if I change the upper bound of `n` to 1.

**Comment by caballa** [comment]
Without `--enable-loop-idiom` SeaHorn  will unroll the loop since it cannot find an universally quantified invariant. With `--enable-loop-idiom` I can see that LLVM will replace the initialization loop with memset. We are not precise with memset.
