### ISSUE TITLE
Understand example involving pointers

### ISSUE THREAD

**Issue by abhcs** [seahorn/seahorn#193]
I am having some trouble understanding an example involving pointers:
```
extern void __VERIFIER_assume (int);                            
extern int  __VERIFIER_NONDET(void);                            
extern void __VERIFIER_error (void) __attribute__((noreturn));  
void sassert (int v) { if (!v) __VERIFIER_error (); }           
#define assume __VERIFIER_assume                                
#define nd __VERIFIER_NONDET                                    
                                                                
int protected = 0;                                              
                                                                
int* get ();                                                    
                                                                
int foo (int* i)                                                
{                                                               
  assume (protected == 0);                                      
  *i = 1;                                                       
  sassert (protected == 0);                                     
  return 0;                                                     
}                                                               
                                                                
int main (void) {                                               
  void *p = get ();                                             
  foo (p);                                                      
  return 0;                                                     
}
```
The command `sea pf x.c` returns `unsat`. This indicates to me that seahorn does not handle pointers soundly because `get` may be defined as:
```
int* get () {
  return &protected;
}
```
which would modify `protected` right before the assertion.

I could also not understand why the example `play/mem/t1.c` returns `unsat`. In this example, I would expect `sat` because `get` could return a constant pointer, and bar may be a noop, which would violate the assertion since `*p = *q = 22`. A comment in the file says that the assertion passes because of aliasing information provided by DSA. Could getting better aliasing information solve the above issues?

**Comment by caballa** [comment]
The pointer analysis used by SeaHorn assumes that external calls returning a pointer  returns a fresh memory region disjoint from the rest. This is a pragmatic choice, otherwise the analysis of real programs would be too imprecise if we would assume that pointers returned by external calls might alias with any other pointer. Similarly, we assume that external calls do not generate extra aliasing between parameters passed to an external call for similar reasons. 

Note that this can be always refined by writing stubs that simulate the aliasing behavior of the external calls. In fact, we have a limited way of doing that by calling special functions understood by our pointer analysis (see https://github.com/seahorn/sea-dsa#dealing-with-cc-library-and-external-calls)

**Comment by abhcs** [comment]
My use-case is a real one. I describe a simplified version next. A program `foo` (code, data, stack, heap) resides in `[LOW, HIGH]` and has access to the full memory range `[0, MAX_ADDRESS]`. An adversary that does not have access to `[LOW, HIGH]` transfers control to `foo (p)` where `p` is unconstrained. The adversary should not be able to make `foo` overwrite protected objects in `[LOW, HIGH]`.

```
int protected = 0;

int foo (int *p) {
  assume (protected == 0);
  int ret = 0;
  int x = *p;
  if (x == 1) ret = 1;
  if (x == 2) ret = 2;
  ...
  if (p < LOW || p > HIGH) *i = ret;
  assert (protected == 0);
  return 0;
}
```

This should return `unsat`. So my problem is not about modeling external calls, it is about modeling the initial environment in which `foo` is called. The initial pointer `p` in this environment is completely unconstrained, and I don't see any obvious way of using the pointer semantics in sea-dsa to deal with that.

**Comment by abhcs** [comment]
In fact, a clearer example would be as follows:
```
typedef struct {
  int *x;
} Buffer;

int protected = 0;

int main (void) {
  Buffer *b = nd ();
  assume (b < LOW || b > HIGH);  // adversary has access to buffer
  adversary (); // adversary havocs all memory in [0, LOW] \/ [HIGH, MAX_ADDRESS]
  protected_old = protected;
  foo (b);
  assert (protected_old == protected);
}

void foo (Buffer *b) {
  if (b->x < LOW || b->x > HIGH) *(b->x) = *(b->x) + 1;
}
```

Here, `foo` looks at a fixed location in memory for a pointer to a communication cell with the adversary. If the cell does not overlap with `[LOW, HIGH]`, it increments the contents of the cell. In this program, `main` just serves as a modeling component for composing some initialization assumptions, some adversarial actions and finally the function call with pre and post conditions. Is it possible to create such a model in seahorn?

**Comment by agurfinkel** [comment]
Every tool must make some default decisions about how to handle under-specified programs. In SeaHorn, the decision is to assume that if something is not specified (i.e., left as external), then it does not access or return pointers to memory allocated by the program. The only exception is that memory analysis determines that external and internal pointer might alias.

Every tool must also provide a default memory manager. In the case of SeaHorn, the default memory manager returns an arbitrary address at each allocation site. There are no guarantees on these addresses. For example, they don't have to be disjoint, unique, etc. 

These default choices can (and should) be changed by the user that has a particular requirements of the memory model. As usual, this is done by providing an implementation of a memory allocator (`malloc`) and not relying on the default behavior of SeaHorn.

For example, we have allocators that model the separation of stack and heap, proper allignment of pointers, uniqueness of allocated regions, etc. The more details are supported by the allocator, the harder is the verification problem. Hence, we don't expose ours and leave the user to decide what they need.

**Comment by abhcs** [comment]
Thanks for the suggestions, they help with some of the problems mentioned in my comment. However, one fundamental problem (that may be specific to the low-level application I am dealing with) is the presence of an unconstrained pointer in the initial environment. To quote Steensgard (and assuming that this applies to dsa like it applies to points-to):

> The analysis tracks flow of pointer values, so the analysis algorithm may produce wrong results for programs that construct pointers from scratch (e.g., by bitwise duplication of pointers) and for non-portable programs (e.g., programs that rely on how a specific compiler allocates variables relative to each other).

Since you rely on an analysis algorithm like dsa to provide you aliasing information, you cannot deal with code that reads external buffers or tables (`b` in my example) to extract pointers (`b->x`). The internal dsa constructs exposed here (https://github.com/seahorn/sea-dsa#dealing-with-cc-library-and-external-calls) do not really help with this problem. It is an interesting problem to see if dsa can be extended to soundly deal with unconstrained pointers.

**Comment by agurfinkel** [comment]
A lot depends on your intended use and application. 

The default memory model for SeaHorn is that memory is allocated as memory objects by dedicated allocation functions. There are no *unconstrained* pointers. Pointer arithmetic does not leave bounds of an allocated object. This is in line with the C semantics and semantics used by the LLVM optimizer. Namely, if your program does not follow this memory model, it will not be correctly compiled and optimized by LLVM either.

However, there are other applications and other memory models. For example, when reasoning about x86 binaries, we use a flat memory model in which memory is one flat array, pointers are indexes into the array, and arbitrary pointer operations are allowed. This memory model is harder to reason about, so we only support bounded reasoning with it.

We also have other memory models (currently only for bounded analysis) that accurately model stack and global variable layout, separation of stack and heap, separation of kernel and user memory, alignment of pointers, etc. 

Depending on your intended application, we might suggest a configuration that would work, or construct (or help you construct) a memory model that correctly models your intended semantics. 

SeaHorn itself is inherently neither sound nor unsound. It is a tool to convert program into logic while preserving some aspects of the operational semantics. We guarantee (or try to) that the logical reasoning is sound with respect to the semantics of the logic and theories involved. By necessity, the conversion from programs to logic is use-dependent. What is sound for one application, might be unsound for another. For that reason, we prefer to focus on the semantics that are modeled, features supported, and what combinations we can reason effectively about.

**Comment by abhcs** [comment]
I have tried to use the flat memory model for my problem before in a different modeling tool but as you predict in your comment, the verification became too gunky in that model. This forced me to move to tools like seahorn because the (default) memory model involving non-overlapping objects was found to be more effective in verification in the literature I read.

However, this default model does not match the initial part of the call graph near the entry point which has unconstrained pointers. (I do understand that the default memory model has no such concept which is why it is ill-suited for this part of my call graph). Another way of seeing this is that the initial part of the call stack is actually more low-level and x86-like, so a flat model applies there, but if it sets things up correctly then upper parts of the call stack are more in line with typical C semantics and I would expect the default model to work there.

My best guess is that I need a hybrid approach (flat for initial function(s), object based for the rest) memory model for my verification to go through. I still need to figure out if two such models can be composed soundly, any suggestions are welcome. I am more interested in verification than in bounded reasoning but will have to be satisfied with the latter if the former does not go through.

**Comment by agurfinkel** [comment]
If you are willing to share the details of your problem (perhaps we can talk offline), we might be able to suggest something. We typically re-design a memory model for every specialized application.

In terms of verification, the issue is what kind of annotations / invariants / summaries must be inferred for verification to go through. With flat memory model, the annotations often require keeping track of what memory is actually being used. This is typically done with separation logic or (implicit) dynamic frames. Neither one has really good automatic inference procedures (and are not currently supported by SeaHorn). However, if your invariants are simpler --- e.g., certain memory does not flow to certain other memory -- then we might be able to do something.

It also might matter on the size of your initial memory. Is it finite? Fixed size? Allocated all at once initially? Our default memory model is often constrained by the need to support arbitrary dynamic allocation. More things are possible if there are some restrictions on allocation that are available.

**Comment by abhcs** [comment]
I can share more details offline. Is there a different preferred channel for such communication (email, ...)?

**Comment by agurfinkel** [comment]
We usually use private channels on gitter: https://gitter.im/seahorn/seahorn
But email works well too :)
