### ISSUE TITLE
Logs for timed out tasks

### ISSUE THREAD

**Issue by aadityanaik** [seahorn/seahorn#195]
If I run `sea pf file.c --cpu=100` and it times out, is there a way to see stats and logs for such timed out tasks, especially for the different components/processes?

**Comment by agurfinkel** [comment]
Unfortunately no. Most time is spend in the underlying SMT solver, so we don't measure statistics for individual steps outside of that. You can get some more visibility into what is happening using `--versbose=1`. You can also use `--horn-stats=true` to see some statistics, but they are only printed for successfully completed runs.

**Comment by caballa** [comment]
Another thing you can try is in branch `deep-dev-5.0` (our current development branch) there is available an option `--max-depth VAL`. This option runs the underlying SMT solver engine for VAL steps. These steps might take seconds or more but the thing is that after VAL is reached, SeaHorn will stop and will print stats as usual. So you can try several values until you figure out how many steps take 100 seconds.

**Comment by aadityanaik** [comment]
@agurfinkel @caballa Thanks for the help!
