### ISSUE TITLE
Unexpected result on array

### ISSUE THREAD

**Issue by oraluben** [seahorn/seahorn#204]
```
int main() {
    int k = __VERIFIER_nondet_int();
    int a[4]; for (int _ = 0; _ < 4; _++) a[_] = 0;

    if (k == 1 && a[k] == 42) __VERIFIER_error();
    return 0;
}
```
expected result: unsat
actual result: sat
command: both `sea bpf test.c` and `sea pf test.c` get unexpected result.

**Comment by caballa** [comment]
What is `for (int _ = 0; _ < 4; _++) a[_] = 0;` ?
Do you mean 

``` 
int i=0;
for (i = 0; i < 4; i++) a[i] = 0;
```

**Comment by agurfinkel** [comment]
Optimization replace the initialization loop with a call to internal `memset`. The call is over-approximated in the current default semantics. The example works as expected with the following options that invoke new, experimental, bit- and memory-precise semantics:
```
