### ISSUE TITLE
Cmake Error & Clang Link Error 

### ISSUE THREAD

**Issue by huxinwen1994** [seahorn/seahorn#205]
Hello, I build seahorn successfully according to https://github.com/seahorn/seahorn.  My Ubuntu's version is 18.04.2 LTS (Bionic Beaver). 
However, I have several questions:

The first one:
When I enter "cmake -DCMAKE_INSTALL_PREFIX=run -DCMAKE_BUILD_TYPE="Release" -DCMAKE_CXX_COMPILER="clang++-6.0" -DCMAKE_C_COMPILER="clang-6.0" -DSEA_ENABLE_LLD="ON" -GNinja -DCMAKE_EXPORT_COMPILE_COMMANDS=1 ../" according to the instructions, I get "CMake Error: Error: generator : Ninja
Does not match the generator used previously: Unix Makefiles
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory."
If I remove these files, there still has error.I installed all packages mentioned. Is there anything I missed?

The second one:
I downloaded "clang+llvm-5.0.0-linux-x86_64-ubuntu16.04" and linked clang, clang++ in bin, but command "cmake --build . --target test-all"  will have errors as below:
"test/CMakeFiles/test-all.dir/build.make:57: recipe for target 'test/CMakeFiles/test-all' failed
make[3]: *** [test/CMakeFiles/test-all] Error 1
CMakeFiles/Makefile2:3776: recipe for target 'test/CMakeFiles/test-all.dir/all' failed
make[2]: *** [test/CMakeFiles/test-all.dir/all] Error 2
CMakeFiles/Makefile2:3783: recipe for target 'test/CMakeFiles/test-all.dir/rule' failed
make[1]: *** [test/CMakeFiles/test-all.dir/rule] Error 2
Makefile:1317: recipe for target 'test-all' failed
make: *** [test-all] Error 2"

The third one:
I tried command "EXPORT SEAHORN=<install_dir>/bin/sea.  I assumed the "<install_dir>" is the directory of "seahorn/build", is this correct? Besides, what should I install or do with "EXPORT: command not found". 

Thanks a lot.

**Comment by caballa** [comment]
For the first question, you need to remove the build directory and compile from scratch again.
For the second question, I don't have enough information to see what is the problem.
For the third question, you need to type `export ...` rather than `EXPORT`.

**Comment by huxinwen1994** [comment]
> For the first question, you need to remove the build directory and compile from scratch again.
> For the second question, I don't have enough information to see what is the problem.
> For the third question, you need to type `export ...` rather than `EXPORT`.
> `<install_dir>` is the directory where you installed seahorn (via option `DCMAKE_INSTALL_PREFIX`). In your case, it's the directory `run`

Hi, I tried your suggestion. The third question was solved.

I removed the build directory and compile from scratch again, but the error is still there:
"CMake Error: Error: generator : Ninja
Does not match the generator used previously: Unix Makefiles
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.
"

I installed Clang with "sudo apt install clang" instead, after linked it, I tested with command "cmake --build . --target test-all". The feedback was:
"Failing Tests (5):
    Seahorn :: solve/01_unsat.c
    Seahorn :: solve/02_unsat.c
    Seahorn :: solve/04_unsat.c
    Seahorn :: solve/05_unsat.c
    Seahorn :: solve/06_unsat.c

  Expected Passes    : 110
  Expected Failures  : 1
  Unexpected Failures: 5

1 warning(s) in tests.
test/CMakeFiles/test-all.dir/build.make:57: recipe for target 'test/CMakeFiles/test-all' failed
make[3]: *** [test/CMakeFiles/test-all] Error 1
CMakeFiles/Makefile2:3776: recipe for target 'test/CMakeFiles/test-all.dir/all' failed
make[2]: *** [test/CMakeFiles/test-all.dir/all] Error 2
CMakeFiles/Makefile2:3783: recipe for target 'test/CMakeFiles/test-all.dir/rule' failed
make[1]: *** [test/CMakeFiles/test-all.dir/rule] Error 2
Makefile:1317: recipe for target 'test-all' failed
make: *** [test-all] Error 2
" 
Besides, command "sea" was not found, I don't know whether these are related to the error in first question.

**Comment by kuhar** [comment]
@huxinwen1994 can you paste the commands you run one-by-one, including creating a fresh build directory and every cmake/make/ninja invocation?
The error message suggests that cmake was invoked multiple times with incompatible options.

**Comment by huxinwen1994** [comment]
@kuhar I ran commands to build in following order: 
1. cd seahorn
2. mkdir build
3. cd build
4. cmake -DCMAKE_INSTALL_PREFIX=run ../ 
5. cmake --build . 
6. cmake --build . --target extra && cmake .. 
7. cmake --build . --target crab && cmake .. 
8. cmake --build . --target install
9. sudo apt install clang
10. cd seahorn/build/run/bin
11. ln -s usr/bin/clang clang
12. ln -s usr/bin/clang++ clang++

and then I ran "cmake -DCMAKE_INSTALL_PREFIX=run -DCMAKE_BUILD_TYPE="Release" -DCMAKE_CXX_COMPILER="clang++-6.0" -DCMAKE_C_COMPILER="clang-6.0" -DSEA_ENABLE_LLD="ON" -GNinja -DCMAKE_EXPORT_COMPILE_COMMANDS=1 ../",
the error message is as follows:
"CMake Error: Error: generator : Ninja
Does not match the generator used previously: Unix Makefiles
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.
"

I don't know if your multiple invocations mean that I can only choose one command in 6, 7, 8 line to install after command line 5(cmake --build), instead of building them at the same time?

**Comment by caballa** [comment]
You are trying to build twice: one at step 4 (with Makefile) and then after step 12 you build again with Ninja. That's the problem. 

What are you trying with running `cmake` again after step 12?

**Comment by huxinwen1994** [comment]
@caballa I see. I'm sorry, this is a ridiculous mistake. 
Thanks a lot.
