### ISSUE TITLE
"In Action" asciinema has been archived

### ISSUE THREAD

**Issue by shiatsumat** [seahorn/seahorn#206]
The asciinema recording in "In Action" of http://seahorn.github.io/ has been archived.
Is there any chance of restoring of the recording?

**Comment by caballa** [comment]
It's in our TODO list. 

Meanwhile, you can check it out the demo videos we made available in one of our posts
http://seahorn.github.io/seahorn/cex/validation/2018/08/03/seahorn-cex-vstte18.html
