### ISSUE TITLE
Static analysis (using clang)

### ISSUE THREAD

**Issue by tal2208** [seahorn/seahorn#215]
Hey,
As part of our final project we need to be able to tell on which variables (from the original .c source file) each relation is declared (the relations of the .smt2 file). 
For example:
this relation - (declare-rel main@_bb (Int Int Int )) 
we want to know who are the 3 integers from the .c source file (x or y or z etc..)

Does anyone know if there is a way to do so? (maybe using clang only and not seahorn)

Thank you!

**Comment by caballa** [comment]
What is the final goal? do you want to print SeaHorn invariants using C names?
Or maybe you want to extract counterxamples  using C names? For the latter, we already produce executable counterexamples which is a much better solution.

**Comment by tal2208** [comment]
We want the first goal you mention.
for cases Z3 outputs "unsat" on a .c file, we want to know who are the variables (using C names from the original .c file) in Z3 "define-fun ..." outputs

**Comment by caballa** [comment]
You need to go from SMT --> LLVM --> C.

In SeaHorn, it's easy to go from SMT to LLVM if you just care about integer variables. SMT arrays are originated from pointer instructions so not sure if mapping back those are straightforward.
More difficult is to go from LLVM to C. Even if you run SeaHorn with debug symbols (by adding the option `-g` to `sea` command things like PHI nodes makes the translation back hard.
Julien Henry tried to do that with Pagai. Take a look at his PhD thesis https://tel.archives-ouvertes.fr/tel-01102418/document at page 136.
