### ISSUE TITLE
[opsem] C++ new keyword being handled as external function

### ISSUE THREAD

**Issue by danblitzhou** [seahorn/seahorn#248]
When dealing with C++ code that uses `new` or `new[]` to dynamically allocate memory, `BvOpSem2` is not able to treat the corresponding llvm instruction correctly (treat like malloc); following the gdb trace, the mangled `new`/`new[]` functions are handled by `visitExternalCall` in `BvOpSem2`, which ignores the instructions.
Example `.bc` code can be found [here](https://gist.github.com/danblitzhou/41374ad19f5e0ab807d060904aa5915b)
Command to repro: `/path/to/seahorn --horn-bmc --keep-shadows=true --horn-sea-dsa --sea-dsa=ci --horn-solve -horn-inter-proc -horn-sem-lvl=mem --horn-step=large -log opsem example.bc --horn-bv2=true`

**Comment by agurfinkel** [comment]
Fixed by d92f9dc

opsem2 does not support heap allocation. It expects all allocations to be promoted to stack `alloca`. Updated our stack promotion pass to replace `operator new` with alloca as well.
