### ISSUE TITLE
Assertion in ShadowDsaImpl::updateReadMod failing

### ISSUE THREAD

**Issue by igcontreras** [seahorn/seahorn#249]
`seahorn` options:
```
sea pf -O2 -g --step=large --track=mem --horn-global-constraints=true --horn-stats \
--enable-nondet-init --strip-extern --externalize-addr-taken-functions \
--horn-singleton-aliases=true --horn-pdr-contexts=600 --devirt-functions \
--horn-ignore-calloc=false --enable-indvar --enable-loop-idiom \
--horn-estimate-size-invars --symbolize-constant-loop-bounds \
--unfold-loops-for-dsa --simplify-pointer-loops --horn-iuc=1 --horn-iuc-arith=1 \ 
--dsa-stats  --horn-sea-dsa-local-mod --dsa=sea-cs --cpu=300 --mem=4096 \ 
example.c
```

Assertion that failed:
```
Assertion failed: (&(m_dsa.getGraph(*cf)) == &G && "Computing local mod/ref in context 
sensitive mode"), function updateReadMod, file ../lib/Transforms/Instrumentation
/ShadowMemSeaDsa.cc, line 1094.
```
[example.c](https://gist.github.com/igcontreras/aaaaeae0fef6d2e01dc1a48244ad1c80) is `c/ldv-linux-3.14/linux-3.14__complex_emg__linux-drivers-clk1__drivers-net-ethernet-intel-e1000-e1000_true-unreach-call.cil.i` in the svcomp.

**Comment by agurfinkel** [comment]
@caballa is that something you are looking at?

**Comment by caballa** [comment]
Not today but I plan to do it tomorrow or Friday.
@igcontreras  will add (I think) few more issues.

**Comment by agurfinkel** [comment]
The assertion checks for incompatible options. Local mod/ref is only re-computed in context insensitive mode. 

We should re-evaluate this code. It was written because llvm-dsa did not provide good mod/ref information. We can probably be do better.

None-the-less. There is nothing to fix. Remove `-horn-sea-dsa-local-mod` and it will work.
