### ISSUE TITLE
[seaopt] type of global variable changed unexpectedly by seaopt

### ISSUE THREAD

**Issue by danblitzhou** [seahorn/seahorn#252]
During the process of `sea pf` pipeline, `seaopt` converted the type of a global variable from `i32` to `i1`, which caused other problems down the line of the pipeline: (possibly during BmcPass)
```
Error: failed to convert to z3: (select(main@%sm67, @msg_buf_size)_0=(1:bv(1)))

Error: Sorts Bool and (_ BitVec 1) are incompatible
```
Example LLVM IR file for repro https://gist.github.com/danblitzhou/0a81e0b9cfb5b7fd8b6145c3c2924a95
command: 
`seaopt -f -funit-at-a-time --simplifycfg-sink-common=false -o  int_bool.out.bc  -O3 --enable-indvar=false --enable-loop-idiom=false --enable-nondet-init=false --unroll-threshold=150 --disable-loop-vectorization=true --disable-slp-vectorization=true int_bool.bc -S`

**Comment by agurfinkel** [comment]
@danblitzhou is this still an issue? I fixed the conversion failure error. Do you still believe that the optimization is incorrect / suspicious?

**Comment by danblitzhou** [comment]
I think the optimization is correct; can no longer reproduce the crash after the fix in opsem. Closing.
