### ISSUE TITLE
CMake cannot find Z3 and LLVM

### ISSUE THREAD

**Issue by saeednj** [seahorn/seahorn#258]
Hello,

I have Z3 built and installed and its related files can be found in standard paths (/usr/lib and /usr/include), and running `z3 --version` gives me `Z3 version 4.8.6 - 64 bit`.

However, when I run cmake on Ubuntu 18.04 with these arguments:
```
cmake -DCMAKE_INSTALL_PREFIX=run -DCMAKE_BUILD_TYPE=Release ..
```
I get the following warning:
```
-- Could NOT find Z3 (missing: Z3_LIBRARY Z3_INCLUDE_DIR Z3_EXECUTABLE) (Required is at least version "4.3.2")
```

The same happens for LLVM. Although an installed version of Yices is found by cmake.

Running the dependency building (`cmake --build .`) works without a problem, but what if I have a custom version of Z3 and LLVM?

Thanks

P.S. My cmake version is 3.10.2.

**Comment by kuhar** [comment]
The CMake is supposed to fail during the first invocation. External dependencies are automatically checked out, so when you execute it again, like specified in the installation instructions, CMake will detect these previousely-checked-out dependencies and continue with them.
See https://github.com/seahorn/seahorn#installation.

Note that newer CMake verisons support fetching dependencies and resuming within the same invocation (https://cmake.org/cmake/help/v3.14/module/FetchContent.html), but SeaHorn doesn't use it.

**Comment by kuhar** [comment]
To clarify, SeaHorn requires LLVM and Z3 to be built with compilation flags compatible with its current configuration, which required these dependencies to be built together with SeaHorn, or carefully prebuilt with appropriate flags. Prebuilt dependencies are here: https://github.com/seahorn/seahorn-ext-deps/releases and can be provided with cmake flags like here: https://github.com/seahorn/seahorn/blob/master/docker/seahorn-full-size-rel.Dockerfile#L29

**Comment by saeednj** [comment]
Thanks!

What I wanted was to be able to point the installation script to an existing version of Z3 instead of fetching and building a predefined version. The second link you sent has the information I need, thanks.
