### ISSUE TITLE
Broken LLVM Assambly export

### ISSUE THREAD

**Issue by jfh1911** [seahorn/seahorn#259]
When executing the full pipeline, i got an error message when omitting LLVM assambly code (using  `sea pf -g --oll file.ll example.c`  ).
The error message is ```errror: Bitcode was not properly read; expexted top-level entity```

I tested this with the example and the latest docker image of seahorn/seahorn using the example file from the [readme](https://github.com/seahorn/seahorn#annotating-c-programs)

Moreover,  when executing `sea horn --oll ass.ll --solve input` a LLVM assemly file is generated, that is not valid, when trying to verify it (load via `lvm::parseIRFile` , verify via `llvm::verifyModule()`).

**Comment by agurfinkel** [comment]
Can you please provide your inputs so that we can reproduce the problem locally.

Your first command line has a mistake. The option is `--oll=out.ll`, not `-o` which has a different interpretation. The second line looks better, but without knowing what `input` is it is impossible to debug. 

Note that `--oll` option is only for debugging. It is not expected to be used by casual users.

**Comment by jfh1911** [comment]
```
/* verification command: sea pf --horn-stats test.c */
#include "seahorn/seahorn.h"
extern int nd();

int main(void) {
    int k = 1;
    int i = 1;
    int j = 0;
    int n = nd();
    while (i < n) {
        j = 0;
        while (j < i) {
            k += (i - j);
            j++;
        }
        i++;
    }
    sassert(k >= n);
}
```

**Comment by jfh1911** [comment]
I used `--oll`, thats just a typo.

is there a different (prefered) way to export the `.ll` file to see, to which locations and variables  the invariants generated are associated to?

**Comment by agurfinkel** [comment]
`sea smt --horn-stats test.c --verbose=1 --oll=out.ll`

Works for me. It is possible that you have multiple versions of clang and a wrong version is picked at some point. SeaHorn currently uses version 5.0

The latest docker is `seahorn/seahorn-llvm5:nightly` 
`docker pull seahorn/seahorn-llvm5:nightly`

**Comment by jfh1911** [comment]
thank you, that solved it
