### ISSUE TITLE
multiplication handling

### ISSUE THREAD

**Issue by roachspray** [seahorn/seahorn#26]
I am not sure if this is a bug or a limitation of certain analyses, so I apologize if my ignorance gets the better of me.

I have the following code I was using to test (cropping some):

```C
int g();
int
main()
{
   int i, j, k;

   i = g();
   __VERIFIER_assume(i > 0);
   __VERIFIER_assume(i < 50);
   j = g();
   __VERIFIER_assume(j > i);
   __VERIFIER_assume(j < 100);
   k = i * j;
   my_vassert(k > 0);
   return 0;
}
```

and with 'sea pf --horn-stats' i am getting false. If I set i = 2, for example, I will get true. 

Am I making a dumb mistake? 

Thank you for any insight,
Best

**Comment by agurfinkel** [comment]
Can you please add your definition of `my_vassert()`.

Officially, though, non-linear arithmetic, i.e., `i*j` is not supported.

**Comment by roachspray** [comment]
@agurfinkel Thanks for the quick response. I see re: i*j… thank you for clarifying. I need to read more carefully, perhaps :)

Sure, the code is:
```C
#define my_vassert(a)  if (!(a)) __VERIFIER_error()
```

Thank you again. 👍
