### ISSUE TITLE
Incomplete/outdated docker instructions

### ISSUE THREAD

**Issue by kuhar** [seahorn/seahorn#264]
The image name and tag is outdated on: https://seahorn.github.io/seahorn/install/docker/2018/02/24/seahorn-with-docker.html
It doesn't explain how to find the newest image and tag either.

The docker link seahorn.github.io points to the old image on dockerhub.

The github readme does not point to the blog post -- perhaps it would a good idea to point straight there, as the docker instructions are not trivially discoverable.

**Comment by agurfinkel** [comment]
Hmm, good point. We probably should not be updating an old blog. 

What does everyone think about pushing current nightly to `seahorn/seahorn`?

**Comment by codersguild** [comment]
I did ```docker pull seahorn/seahorn:nightly``` to get the docker thing working

**Comment by agurfinkel** [comment]
that one is a fairly old version. Current stable is `seahorn/seahorn-llvm5:nightly`
current development is `seahorn/seahorn-llvm10:nightly`

**Comment by codersguild** [comment]
Thanks for informing me.

**Comment by codersguild** [comment]
Is this docker image using the latest LLVM release? What verison does it use? 
```seahorn/seahorn-llvm10:nightly```.

**Comment by agurfinkel** [comment]
It is based on LLVM10 distribution from llvm.org. Details are in the docker file: 

https://github.com/seahorn/seahorn/blob/dev10/docker/buildpack-deps-seahorn.Dockerfile#L37
