### ISSUE TITLE
Discharge assertions using only Crab backend?

### ISSUE THREAD

**Issue by wuestholz** [seahorn/seahorn#27]
@agurfinkel @lememta @caballa I would like to use the Crab backend not just for inferring invariants, but also for discharging assertions and reporting errors. It seems like this is currently not supported. Is this correct? If so, would it be difficult to add this?

**Comment by caballa** [comment]
Crab has currently support for checking assertions but Crab takes just a CFG-based language as input.

The next thing would be Crab-llvm (https://github.com/seahorn/crab-llvm)  which translates C into LLVM bitcode and then translates to the Crab CFG language.

We would need to add some support in Crab-Llvm but it should be straightforward. There is already code that can translate an assertion from bitcode  to Crab. Then, the other thing would be a simple LLVM pass transformation that removes assertions that can be proven by Crab. I think there is also some code you could reuse. 

In that way you could feed the resulting bitecode to SeaHorn or any other LLVM-based verification tool. Is this what you need? If yes, I can help you with that.

**Comment by wuestholz** [comment]
@caballa Thank you for the quick response. Actually, I need even less. :) Removing the assertions from the bitcode is not really necessary for me. It would be good enough if I would get warnings about assertions that Crab wasn't able to prove safe.

More concretely, it would be great if there was a Seahorn flag (e.g., "--crab-check-assertions") that will use Crab to check the assertions and to report any assertions that could not be proved. Do you think this is possible?

**Comment by caballa** [comment]
Definitely. I will see if it can give support for that quickly. Otherwise I
can tell you what it needs to be done

**Comment by wuestholz** [comment]
@caballa Great! Thank you!

**Comment by wuestholz** [comment]
@caballa Did you have a chance to look into this? Since we depend on this feature I would also be happy to help.

**Comment by caballa** [comment]
I will reply to you with a private email.

Cheers.

On Tue, May 31, 2016 at 4:04 PM, Valentin Wüstholz <notifications@github.com
