### ISSUE TITLE
Crash while producing cex

### ISSUE THREAD

**Issue by parvmor** [seahorn/seahorn#271]
Following program results in a crash when asked to provide a cex (works fine with `sea pf code.c`).

```
#include "seahorn/seahorn.h"
extern int unknown1(void);

 int main(void) {
 int x=1; int y=1;
 while(unknown1()) {
   int t1 = x;
   int t2 = y;
   x = t1+ t2;
   y = t1 + t2;
  }
   sassert(y < 1);
   return 0;
 }
```

Crash log: [log.txt](https://github.com/seahorn/seahorn/files/4166413/log.txt), Branch: master

I see that #154 is a related bug. However, the expected error message is now missing.

**Comment by caballa** [comment]
I cannot reproduce your problem. 

If I run `sea exe-cex -O0 --verify code.c`
I get the expected message `__VERIFIER_error was executed`.
If I run `sea exe-cex  --verify code.c` which uses -O3 the program gets too simple once it's unrolled by the BMC engine. So I get the expected message:
```
sat
ERROR in cex generation: cex trace contains only the entry block but it should contain some more blocks.
The cex produced by the back-end solver is not enough to produce a bmc trace.
This typically happens if the program is too simple.


The harness was not generated. Aborting ...
```

**Comment by parvmor** [comment]
This is strange. I was generating cex by `sea pf --cex=cex.ll code.c` which resulted in that error. Using `-O0` (with `pf`) resulted in a different log. Using `sea exe-cex -O0 --verify code.c` results in: `error: Bitcode was not properly read; Invalid record`. This might be because of my local build. Let me try building the docker image and get back to you.

**Comment by parvmor** [comment]
OK, so building it in docker works fine. I rechecked my local build and it seems good to me, but the crash still pertains. Let me know what I  can provide if you wish to debug this behavior.

Thanks!

**Comment by agurfinkel** [comment]
`error: Bitcode was not properly read; Invalid record` indicates that you have a mix up of different versions of LLVM. `SeaHorn` uses `clang` and `clang++` by looking for them on your machine. However, it does not check that they are the right version. 

The easiest way to ensure that seahorn uses the right version of the tools is to put link to the correct version in the same directory as `sea` script. For example, if SeaHorn is installed in `/User/me/seahorn`, do 

```
$ cd /User/me/seahorn/bin ; ln -sf PATH-TO-LLVM-5/bin/clang . ; ln -sf PATH-TO-LLVM-5/bin/clang++ . 
```

**Comment by parvmor** [comment]
Thanks, that fixed the `Bitcode was not properly read` problem. The local build still crashes with `sea exe-cex -O0 --verify code.c`. So, I am going to use the docker build from now on.
