### ISSUE TITLE
Boost Compilation Issue

### ISSUE THREAD

**Issue by davidtr1037** [seahorn/seahorn#286]
I am trying to compile seahorn with gcc 5.4.0 on Ubuntu 16.04.
When I run:
```
cmake --build . --target install
```
I get the following messages:
```
[ 34%] Linking CXX executable ../../bin/seadsa
../../lib/libSeaDsaAnalysis.a(Graph.cc.o): In function `__static_initialization_and_destruction_0':
/usr/include/boost/system/error_code.hpp:221: undefined reference to `boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:222: undefined reference to `boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:223: undefined reference to `boost::system::system_category()'
collect2: error: ld returned 1 exit status
sea-dsa/tools/CMakeFiles/seadsa.dir/build.make:130: recipe for target 'bin/seadsa' failed
make[2]: *** [bin/seadsa] Error 1
CMakeFiles/Makefile2:2283: recipe for target 'sea-dsa/tools/CMakeFiles/seadsa.dir/all' failed
make[1]: *** [sea-dsa/tools/CMakeFiles/seadsa.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
```

**Comment by agurfinkel** [comment]
old version of boost. upgrade boost. see `docker` directory for compilation instructions

**Comment by davidtr1037** [comment]
Overriding the existing boost version in Ubuntu 16.04 (those in /usr/lib/x86_64-linux-gnu/) is  problematic.

Assuming that I want to build seahorn outside of docker, how can make seahorn use a newer boost version?
From a quick grep, I found the CUSTOM_BOOST_ROOT variable, but not where and how to use it...

**Comment by caballa** [comment]
install boost wherever you want and then pass option `-DBOOST_ROOT=your_path_to_boost` to cmake

**Comment by davidtr1037** [comment]
Thanks guys, successfully built.
