### ISSUE TITLE
Golang frontend for seahorn 

### ISSUE THREAD

**Issue by codersguild** [seahorn/seahorn#293]
Creating a ```golang``` based seahorn frontend that can be used to check assertions for golang based programs. 

The current frontend and the example uses ```C``` as an the coding language for checking and proving assertions. Can the same be done for ```golang``` programs? 

As an alternate is it possible to have bindings for ```seahorn``` in ```golang``` that can directly translate to ```__VERIFICATION_error()``` function in the resulting LLVM bitcode file, i.e. ```.bc``` file.

**Comment by agurfinkel** [comment]
This is an interesting direction, but we are not pursuing it at the moment. I do not know much about golang tools. Do they typically go through LLVM? 

Our short experience with Rust was not very positive. Supporting a new front-end requires supporting the idiomatic way that the front-end uses LLVM. This is often quite intricate. 

We have experimented with front-ends for x86 and solidity. Extra languages would be great to have, but possibly not a trivial task. We would be happy to support you along the way should you want to do try developing such a front-end yourself.

**Comment by codersguild** [comment]
It will be useful to work on this since I intend to use Seahorn along with golang. 
Go programs do not typically use the LLVM infrastructure for building but there is a way to 
compile go programs into LLVM bitcode.

**Comment by caballa** [comment]
Which properties are you interested in? One of the reasons why people like Go is its rich support for concurrency.

**Comment by codersguild** [comment]
I want to start with simple asserts like checking ranges, values, array bounds, type etc and then move on to concurrency.

**Comment by agurfinkel** [comment]
This sounds like a fun project. We would be happy to support it. Good luck!

**Comment by codersguild** [comment]
Thanks for the update.
