### ISSUE TITLE
Spacer/Z3 fails with small step and interproc encoding

### ISSUE THREAD

**Issue by caballa** [seahorn/seahorn#3]
I think this error has been there for a while.
The commands are:

`clang -c -emit-llvm ntdrivers-simplified/cdaudio_simpl1_false-unreach-call_true-termination.cil.c -o cdaudio_simpl1_false-unreach-call_true-termination.cil.bc`

`seapp cdaudio_simpl1_false-unreach-call_true-termination.cil.bc -horn-mixed-sem -o  cdaudio_simpl1_false-unreach-call_true-termination.cil.mixed.pp.bc`

`seahorn cdaudio_simpl1_false-unreach-call_true-termination.cil.mixed.pp.bc -horn-inter-proc -horn-solve`

produces the error:

ASSERTION VIOLATION
File: ../src/ast/ast.cpp
Line: 2484
to_app(get_fact(p2))->get_arg(0) == get_fact(p1)
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB

**Comment by agurfinkel** [comment]
@jorgenavas This seems to have something to do with covers. Triggers an issue deep inside proof-producing portion of Z3. Similar to an issue we had before.

Seems to work using `z3_smt2.py` script. So should work with `seahorn_inter.py`. Let me know how urgent this is. I'll try to look into it on the weekend. A quick look now tells me that it is different (but similar) to the other time this assertion was triggered.

**Comment by caballa** [comment]
This is a too old issue. Several versions of spacer/seahorn since then.
