### ISSUE TITLE
Question: Mixed-Boolean-Arithmetic Assertions

### ISSUE THREAD

**Issue by fvrmatteo** [seahorn/seahorn#321]
Hi!

I decided to do some black-box tests, trying to verify a couple of assertions containing the comparison between a Mixed-Boolean-Arithmetic expression and its non-obfuscated equivalent. The idea mostly came from other reverse engineering resources I found, mentioning the usage of Abstract Interpretation as a "tool" to break or aid with the analysis of some types of obfuscation (e.g. opaque predicates).

I followed the examples in the repositories and implemented the symbolisation of two 32 bits variables **x** and **y** that are then used to implement assertions based on the comparison between the obfuscated and non-obfuscated expressions.

```
#include "seahorn/seahorn.h"

extern void __CRAB_assume (int);
extern void __CRAB_assert(int);
extern unsigned int  __CRAB_nd(void);

int main() {
  unsigned int x = __CRAB_nd();
  unsigned int y = __CRAB_nd();

  // Mixed-Boolean-Arithmetic rewrite rule for the MUL operator (non-linear)
  unsigned int mba1 = ((x & y) * (x | y) + (x & (~y)) * ((~x) & y));
  unsigned int sol1 = (y * x);

  // Clam and SeaHorn asserts
  sassert(mba1 == sol1);
  __CRAB_assert(mba1 == sol1);

  // Mixed-Boolean-Arithmetic rewrite rule for the ADD operator (linear)
  unsigned int mba2 = (x | y) + y - ((~x) & y);
  unsigned int sol2 = (x + y);

  // Clam and SeaHorn asserts
  sassert(mba2 == sol2);
  __CRAB_assert(mba2 == sol2);

  return 0;
}
```

For the tests I used the latest Docker images for **Clam** and **SeaHorn** with the commands:

- `clam.py --crab-dom=term-int --crab-check=assert --crab-sanity-checks mba_demo.c`
- `sea pf -m64 --crab --crab-dom=term-int mba_demo.c`

I selected the `term-int` domain because it's mentioned that it supports non-linear arithmetic expressions.

Results:

- In the **Clam** case the amount of total safe checks is 0 and the amount of total warning checks is 2, hence it resulted in a failure.
- In the **SeaHorn** case the result is **sat**, but the generated counter examples don't seem to be valid. Although disabling the MUL assertion and using the option `--bmc=mono` correctly gives the expected **unsat** result (although I assume this means that internally the SMT prover has been used to verify the equivalence). Enabling the MUL assertion makes the problem unsolvable in a limited amount of time (as expected if the SMT solver it's really used for the equivalence).

So I was wondering:

- Is there any configuration (e.g. another domain) that could enable any kind of useful analysis on the proposed assertions?
- Is the problem I'm trying to approach unfeasible (at the moment) in the Abstract Interpretation field?

Abstract Interpretation it's a whole new field to me and it's likely that the kind of tests I'm doing are not in line with what is expected, so I apologise if the questions are dumb.

**Comment by caballa** [comment]
Unfortunately, your example is beyond what the term domain can do. The term domain extends a numerical domain with uninterpreted functions (UF). The use of UF is what makes the domain able to reason about non-linear expressions but in a very limited way. The correctness of your example relies on intricate rewriting rules for which a more specialized domain is needed. 

Thus, Clam cannot handle this kind of examples. SeaHorn with its invariant generation engine cannot either but the BMC engine can, as you noticed already. 

If you know in advance all the possible rewriting rules it might be possible to extend the term domain. But that certainly would be a research project. Let me know if you are interested in going in that direction. I might be able to help.

**Comment by fvrmatteo** [comment]
Thank you for your prompt reply!

In specific cases some of the rewriting rules are known in advance (e.g. in obfuscators that don't regularly update their rewriting rules), but the effort would be useless in more advanced contexts, as the original Mixed-Boolean-Arithmetic paper describes a generic way to derive novel rewriting rules of increasing algebraically order.

At the moment I'm investigating sound program synthesis approaches to tackle the problem and I don't feel knowledgeable enough to pursue a research project in a field that I don't know (Abstract Interpretation), but thanks a lot for your offer to help. Maybe someone in the future will be interested in the topic. I know that some academic researchers successfully applied Abstract Interpretation to similar problems, so I think more papers on the topic will pop up in the future.
