### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by sahilbhatia17** [seahorn/seahorn#383]
I am trying to build seahorn on Ubuntu 20.04.1. 
I ran the commands mentioned in the installation guide.

I am getting the following error at the command cmake --build . :
[ 11%] Performing download step (SVN checkout) for 'llvm'
svn: E170011: Repository moved temporarily to 'https://llvm.org/svn/llvm-project/llvm/tags/RELEASE_500/final'
make[2]: *** [CMakeFiles/llvm.dir/build.make:92: llvm-prefix/src/llvm-stamp/llvm-download] Error 1
make[1]: *** [CMakeFiles/Makefile2:278: CMakeFiles/llvm.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

I have installed svn also using "sudo apt install subversion".

**Comment by agurfinkel** [comment]
You are using very old version. Please use dev10 branch and instructions there. Easiest is to use provided docker containers (see docker directory). Either use the docker or follow the same instructions on your machine.
