### ISSUE TITLE
[dev10] __VERIFIER_error is ignored inside __VERIFIER_assert

### ISSUE THREAD

**Issue by mchalupa** [seahorn/seahorn#398]
If `__VERIFIER_error` is called from inside `__VERIFIER_assert`, it is discarded.

To reproduce, run `sea pf` on this code:

```C
void __VERIFIER_assert(int x) {
        if (!x)
                __VERIFIER_error();
}

int main(void) {
        __VERIFIER_assert(0);
}
```

The answer is `unsat`. If `__VERIFIER_assert` is renamed to something else, the answer is `sat`. I used the nightly docker build of `dev10` branch.

I see that `__VERIFIER_assert` is declared in `seahorn.h`, so I guess it is handled somehow special. But deleting the definition and using just `__VERIFIER_assert` as `assert` does not work either.

If this is the expected behavior, maybe it could be worth mentioning in README?

**Comment by agurfinkel** [comment]
thank you! did not think of this use case. fixed.
