### ISSUE TITLE
problem with cex

### ISSUE THREAD

**Issue by caterinaurban** [seahorn/seahorn#4]
`/seahorn/build/run/bin/seahorn tmp/example1.pp.ms.o0.bc  -horn-sem-lvl=mem -horn-step=large -horn-solve -horn-stats -horn-cex -log cex`

https://dl.dropboxusercontent.com/u/1889853/example1.pp.ms.o0.bc

**Comment by agurfinkel** [comment]
The input is too simple. Z3 simplifies it too much and a start of the counter-example is lost. The underlying problem is with the fact that it uses bit-vector semantics too heavily and these are abstracted away by non-determinism.
