### ISSUE TITLE
Have trouble building master on Ubuntu

### ISSUE THREAD

**Issue by Andrewfeng123** [seahorn/seahorn#412]
**Describe the bug**
CMake configuration error while running CMakeLists.txt. I have installed LLVM-5 and z3 4.8.11; I've also specified their locations when calling cmake in command line (see below).

**To Reproduce**
1. Clone master branch
2. In seahorn directory, `mkdir build && cd build`
3. `cmake -DCMAKE_INSTALL_PREFIX=run -DCMAKE_BUILD_TYPE="Release" -DCMAKE_CXX_COMPILER="clang++-5.0" -DCMAKE_C_COMPILER="clang-5.0" -DSEA_ENABLE_LLD="ON" -GNinja -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DZ3_INCLUDE_DIR=/usr/include -DZ3_LIBRARY=/usr/lib/libz3.so -DZ3_EXECUTABLE=/usr/bin/z3 -DZ3_ROOT=/usr/bin -DLLVM_DIR=/usr/lib/llvm-5.0/cmake ../`

**Expected behavior**
Trying to build master branch of seahorn.

**Logs, Stacktraces, and Screenshots**
Here is the error message from CMake.
<pre> $ cmake -DCMAKE_INSTALL_PREFIX=run -DCMAKE_BUILD_TYPE=&quot;Release&quot; -DCMAKE_CXX_COMPILER=&quot;clang++-5.0&quot; -DCMAKE_C_COMPILER=&quot;clang-5.0&quot; -DSEA_ENABLE_LLD=&quot;ON&quot; -GNinja -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DZ3_INCLUDE_DIR=/usr/include -DZ3_LIBRARY=/usr/lib/libz3.so -DZ3_EXECUTABLE=/usr/bin/z3 -DZ3_ROOT=/usr/bin -DLLVM_DIR=/usr/lib/llvm-5.0/cmake ../
-- Boost 1.55 found.
-- Found Boost components:
   system
Found Z3 at /usr/bin/z3
Found Yices2 at 
-- Found LLVM 5.0.1
-- Using LLVMConfig.cmake in: /usr/lib/llvm-5.0/cmake
-- Linker detection: GNU ld
CMake Error at /usr/lib/llvm-5.0/lib/cmake/llvm/CheckCompilerVersion.cmake:38 (message):
  Host Clang must be able to find libstdc++4.8 or newer!
Call Stack (most recent call first):
  /usr/lib/llvm-5.0/lib/cmake/llvm/HandleLLVMOptions.cmake:9 (include)
  CMakeLists.txt:220 (include)
</pre>

If I change HandleLLVMOptions.cmake so it skips this check, CMake still complains that 
<pre>CMake Warning at /usr/lib/llvm-5.0/lib/cmake/llvm/HandleLLVMOptions.cmake:185 (message):
  -fPIC is not supported.
Call Stack (most recent call first):
  /usr/lib/llvm-5.0/lib/cmake/llvm/HandleLLVMOptions.cmake:213 (add_flag_or_print_warning)
  CMakeLists.txt:220 (include)

-- Performing Test SUPPORTS_FVISIBILITY_INLINES_HIDDEN_FLAG
-- Performing Test SUPPORTS_FVISIBILITY_INLINES_HIDDEN_FLAG - Failed
-- Performing Test C_SUPPORTS_WERROR_DATE_TIME
-- Performing Test C_SUPPORTS_WERROR_DATE_TIME - Failed
-- Performing Test CXX_SUPPORTS_WERROR_DATE_TIME
-- Performing Test CXX_SUPPORTS_WERROR_DATE_TIME - Failed
-- Performing Test CXX_SUPPORTS_CXX11
-- Performing Test CXX_SUPPORTS_CXX11 - Failed
CMake Error at /usr/lib/llvm-5.0/lib/cmake/llvm/HandleLLVMOptions.cmake:402 (message):
  LLVM requires C++11 support but the &apos;-std=c++11&apos; flag isn&apos;t supported.
Call Stack (most recent call first):
  CMakeLists.txt:220 (include)
</pre>

**Desktop (please complete the following information):**
 - Ubuntu 18.04
 - LLVM 5.0
 - z3 4.8.11
 - 
![Screenshot from 2021-06-21 02-44-29](https://user-images.githubusercontent.com/19532712/122718799-596ab180-d23b-11eb-8582-dcf078d590c7.png)

Any help would be greatly appreciated, I have been stuck trying to build seahorn for quite a while now! Thank you!

Also, CMakeLists.txt seems a bit out of date since 
![Screenshot from 2021-06-21 02-58-53](https://user-images.githubusercontent.com/19532712/122719773-aa2eda00-d23c-11eb-92f3-9f01e1355d1c.png) no longer works.

**Comment by caballa** [comment]
master is obsolete. Use branch dev10. More details here https://github.com/seahorn/seahorn/issues/405#issuecomment-855926156
