### ISSUE TITLE
SAT solver result mismatch with actual executable

### ISSUE THREAD

**Issue by crides** [seahorn/seahorn#430]
Hi, I've been trying to use seahorn to verify part of [my firmware](https://github.com/crides/steno/tree/mbeddr), specifically that a string manipulation function is equivalent to a set of regex rules. I'm using a command line as follows:

```sh
steno/qmk $ sea exe-cex -o ortho_test -I. ortho_test.c orthography.c mregexp/mregexp.c
```

which prints `sat` in the middle, meaning that the assertions failed. However after executing the counterexample executable (`./ortho_test`), there's no `__VERIFIER_error reached` printed out, so that assertions didn't fail. Reading some other issues it seems like this can happen with non-linearity, but I don't think there's anything like that happening here. This is done using the docker container `seahorn/seahorn-llvm10`

**Comment by crides** [comment]
Hi, thanks for the quick reply (I don't know why I didn't see it until now). I'll look at the repo you provided and see where I can get from there

**Comment by caballa** [comment]
I'll close this issue for now. Let us know if there are still other issues.
