### ISSUE TITLE
Error installing seahorn

### ISSUE THREAD

**Issue by jcrreis** [seahorn/seahorn#440]
When i try to install seahorn, i get the following error:

```
-- Could NOT find Z3 (missing: Z3_INCLUDE_DIR Z3_EXECUTABLE) (Required is at least version "4.8.10")
CMake Warning at CMakeLists.txt:148 (message):
  No Z3 found.  Run

  	cmake --build .  && cmake /home/joao/Desktop/seahorn
```

However when i type ```z3 --version```

I get this:

```
Z3 version 4.8.17 - 64 bit
```
Can you give me some help?

Thank you.

**Comment by agurfinkel** [comment]
Looks like you do not have the right version of Z3 installed on your system and/or did not tell seahorn where to find it.

The easiest way to create a build of seahorn is to use the provided docker container. You can use the container as is (i.e., as a binary), or use instructions from the docker files to build one yourself.

The use the nightly container do
```
docker pull docker pull seahorn/seahorn-llvm10:nightly
```

Instructions to build in a docker container are here: https://github.com/seahorn/seahorn/blob/dev10/docker/seahorn-builder.Dockerfile

Note that the main development branch is currently `dev10`

Hope this helps,
arie
