### ISSUE TITLE
Expose number of values in counter example

### ISSUE THREAD

**Issue by foonathan** [seahorn/seahorn#457]
**Is your feature request related to a problem? Please describe.**

I'm using SeaHorn to analyze [Structured Text](https://en.wikipedia.org/wiki/Structured_text). Structured Text programs always run in an infinite loop reading new input. I'm thus generating a main function that looks like this in C:

```c
int nondet_input_value();

int main()
{
      while (true)
      {
            int input = nondet_input_value();
            execute_one_cycle(input);
      }
}
```

When SeaHorn generates a counter example, it implements `nondet_input_value()`  so that it returns up to `N` input values, where `N` is the first cycle with a failed assertion. Normally, you'd then link that counter example against your program code and use a debugger to test it. I can't do that, however.

Instead, I link it against a program that just prints the input values from the counter example. The issue here is that I have no way of knowing how many input values SeaHorn provides. The current solution of an infinite loop isn't ideal.

**Describe the solution you'd like**
Currently, the counter example module exposes only an implementation of the function. I'd also like it to expose a constant containing the number of input values it generated, something like this:

```ll
@__seahorn_cex_count = constant i16 2 ; This line is new.
@0 = private constant [2 x i16] [i16 364, i16 32492]
@1 = private global i32 0

declare i16 @__seahorn_get_value_i16(i32, i16*, i32)

define i16 @nondet_input_value() {
entry:
  %0 = load i32, i32* @3, align 4
  %1 = add i32 %0, 1
  store i32 %1, i32* @3, align 4
  %2 = call i16 @__seahorn_get_value_i16(i32 %0, i16* getelementptr inbounds ([2 x i16], [2 x i16]* @2, i32 0, i32 0), i32 2)
  ret i16 %2
}
```

**Comment by agurfinkel** [comment]
I'm trying to understand what exactly is required. 

Different nondet functions might have different number of values. So a single value for all functions does not work in general. At the same time, the constant for each array is already available in the type.

The function `nondet_input_value()` knows how many inputs are available and will return `0` when the input array is exhausted.

Perhaps we can synthesize `nondet_input_value_size()` function that returns the size...

**Comment by foonathan** [comment]
> Different nondet functions might have different number of values. So a single value for all functions does not work in general. 

Ah, okay, I wasn't aware.

> At the same time, the constant for each array is already available in the type.

The issue is that the array is private, and so is this type. I currently have a program like this, that I link against the counter example.

```cpp
int nondet_input_value();

int main()
{
      while (true)
      {
            int input = nondet_input_value();
            std::printf("%d\n", input);
      }
}
```

I'd like to put something other than `true` in that loop condition, so I can terminate.

> Perhaps we can synthesize nondet_input_value_size() function that returns the size...

That would be one option. Alternatively, the constant can be the maximum of all values. This is what I would actually need to compute in the presence of multiple inputs.

**Comment by agurfinkel** [comment]
fixed

**Comment by foonathan** [comment]
Thanks, that was really quick!

**Comment by agurfinkel** [comment]
I haven't had a lot of time to test it, so let me know if you run into issues with it.
