### ISSUE TITLE
The command "sea abc test.c" does not work

### ISSUE THREAD

**Issue by yiyuaner** [seahorn/seahorn#464]
According to https://github.com/seahorn/seahorn/issues/194:

> The command sea abc --abc-dsa=sea-cs test.c should add assertions to check that each nontrivial memory access is safe and then it will try to prove those assertions.

However, I get the following result:
```
sea: error: argument parser: invalid choice: 'abc' (choose from 'bpf', 'bnd-fe', 'cut-l
oops', 'bnd-smt', 'pf', 'smt', 'clp', 'lfe-smt', 'lfe-clp', 'clang', 'pp', 'ms', 'opt',
 'horn', 'horn-clp', 'boogie', 'fe', 'lfe', 'crab-inst', 'crab', 'unroll', 'clang-pp', 
'inc-smt', 'term', 'ndc-inst', 'ndc', 'linkrt', 'wmem', 'exe', 'inspect-bitcode', 'insp
ect', 'smc', 'rmtf', 'fpf', 'fpcf', 'spf', 'yama', 'cex', 'exe-cex')
```
I am using the docker `seahorn/seahorn-llvm10:nightly`.

Hope for your help, thanks.

**Comment by caballa** [comment]
Unfortunately, `abc` option has not been ported to LLVM 10 onward because of lack of users
The last workable version is in master branch that it's really old (LLVM 5.0) (https://github.com/seahorn/seahorn/blob/master/lib/Transforms/Instrumentation/BufferBoundsCheck.cc)

**Comment by caballa** [comment]
One thing you can do is to try that old version (https://hub.docker.com/repository/docker/seahorn/seahorn-llvm5).
Maybe if you get enthusiastic enough you can help with the porting to LLVM 14 ;-)
