### ISSUE TITLE
Questions about executable counterexample and type conversion.

### ISSUE THREAD

**Issue by bfsyrgz** [seahorn/seahorn#499]
```
//example.c
#include "seahorn/seahorn.h"
int main() {
  unsigned int A[2];
  unsigned int B[2];
  double n = 1.01;

  for(int i = 0; i < 2; i++){ 
  	A[i] = i - n;
  	B[i] = i - n;
  }

  for(int i = 0; i < 2; i++) {
  	sassert(A[i] == B[i]) ;
  }

  return 0;
}
```
In this case, I run ```sea bpf -m64 example.c``` and SeaHorn gave the **sat** result. So I ran the following commands ```sea bpf --cex=witness.ll example.c```, ```sea exe -m64 -g example.c witness.ll -o example.exe``` , ```./example.exe``` in turn to see the executable counterexample. But the ```.exe``` dit not have any output on the terminal, that is, I did not see the information "```[sea] __VERIFIER_error was executed```".

Then I arbitrarily changed the value of ```n``` (e.g. 2.0, 343.00, 4.123, etc.) and found that when the fractional part of ```n``` is 0, the result of the command is **unsat**, otherwise, the result is **sat**.

I have the following questions:

1. For the ```sat``` result of ```example.c```, why does the executable counterexample not give the message "```[sea] __VERIFIER_error was executed```"? Is it because SeaHorn checks for something other than ```assert();``` statement in the code?

2. For this example involving type conversion, why does SeaHorn validate differently on whether the fractional part of a floating-point number is zero?

Please help me to explain this situation. Thanks.

Version: seahorn 14.0.0
OS: ubuntu 22.04

**Comment by caballa** [comment]
Seahorn does not support floating points. My guess is that when n=1.0 LLVM cast it to an integer.
