### ISSUE TITLE
-m32 and -m64 generate different results.

### ISSUE THREAD

**Issue by bfsyrgz** [seahorn/seahorn#501]
```
//example.c
#include  "seahorn/seahorn.h"

union T {
  long l;
  struct {
    char b3, b2, b1, b0;
  } c;
};

int f(union T u) {
  ++u.c.b0;
  ++u.c.b3;
  return (u.c.b1 != 2 || u.c.b2 != 2);
}

int main() {
  union T u;
  u.c.b1 = 2;
  u.c.b2 = 2;
  u.c.b0 = ~0;
  u.c.b3 = ~0;

  union T u_1 = u;
  
  //initial_block
  if( 0 ) {
    abort();
  } else if( (f(u)) ) {
    abort();
  }
  
  //transformation_block
  if( 0 || (f(u_1)) ) {
    abort();
  }
  
  //conditionStmt
  sassert(u.l == u_1.l) ;

	return 0;
}
```

I used ```clang -m64 example.c``` and ```clang -m32 example.c``` to compile ```example.c```, then ran their executables. Both results showed that the condition ```u.l == u_1.l``` in ```assert()``` statement is true. However, I respectively ran ```sea bpf -m64 example.c``` and ```sea bpf -m32 example.c``` , ```-m64``` gave **sat** result and ```-m32``` gave **unsat** result. 

In ```example.c```, the variable ```u``` has been assigned before it is used. I don't understand why SeaHorn gave different results than compiler Clang. Please help me to explain this situation. Thanks.

Version: seahorn 14.0.0
OS: ubuntu 22.04

**Comment by caballa** [comment]
I think it has to do again with undefined behavior (UB). With -m32, the size of a `long` is 4 bytes so there is no UB. However, with `-m64` the size of a `long` is 8 bytes. So with `-m64` when you compare `u.l == u_1.l` 4 bytes will be uninitialized.  

The reason why SeaHorn seems to deal with UB differently than Clang is that SeaHorn runs **always** Clang with `-O1` and then it performs its own LLVM optimizations. One of these optimizations replaces `undef` LLVM values with non-deterministic values. This option is called `rename-nondet` and it's set to _true_ by default.  This option was originally designed to deal with programs from SV-COMP but it should be probably set to false by default. I also noticed that the option cannot be set via python scripts (e.g., `sea` script) and it's only accessible via the `seapp` executable.

**Comment by caballa** [comment]
I think it has to do again with undefined behavior (UB). With -m32, the size of a `long` is 4 bytes so there is no UB. However, with `-m64` the size of a `long` is 8 bytes. So with `-m64` when you compare `u.l == u_1.l` 4 bytes will be uninitialized.  

The reason why SeaHorn seems to deal with UB differently than Clang is that SeaHorn runs **always** Clang with `-O1` and then it performs its own LLVM optimizations. One of these optimizations replaces `undef` LLVM values with non-deterministic values. This option is called `promote-nondet-undef` and it's set to _true_ by default.  This option was originally designed to deal with programs from SV-COMP but it should be probably set to false by default. I also noticed that the option cannot be set via python scripts (e.g., `sea` script) and it's only accessible via the `seapp` tool executable.

**Comment by caballa** [comment]
To get the same behavior than Clang, update SeaHorn and use the command `sea bpf -m64 --promote-nondet-undef=false`
