### ISSUE TITLE
SeaHorn gives an unexpected result when another function is called to change the value of a variable. 

### ISSUE THREAD

**Issue by bfsyrgz** [seahorn/seahorn#505]
**example.c**
```
#include  "seahorn/seahorn.h"
#include <string.h>

void foo(char *p, unsigned long *r) {
  unsigned long n0 = strlen(p);
  *r = n0;
}

int main() {
  char a[4] = "";
  strcpy(a, "123");
  
  unsigned long n2;
  
  foo(a, &n2);
  
  sassert(n2 == 3);

  return 0;
}
```
In this case, I run ```sea bpf -m64 --promote-nondet-undef=false example.c```. I don't understand why SeaHorn gave  the unexpected result ```sat```. Is it related to the pointer parameter of function ```foo()```?

**Comment by caballa** [comment]
Btw, I should have said that you should run `bpf --bmc=opsem` which runs the bounded model checker but with a more precise modeling of the C semantics.

In any case, if you run `sea bpf --bmc=opsem  --promote-nondet-undef=false ../test_505.c`

You should see a warning message:

```
Warning: unhandled instruction:   %_2 = call i32 @strlen(i8* noundef nonnull dereferenceable(1) %_1) #8 @ entry in main (BvOpSem2.cc:3433)
```

so `strlen` is treated as a nondeterministic call which is not precise enough to prove your assertion.
