### ISSUE TITLE
Does seahorn support common memory manipulation functions?

### ISSUE THREAD

**Issue by Elowen-jjw** [seahorn/seahorn#506]
```
#include <string.h>
#include "seahorn/seahorn.h"

#define N 10

int a[N];
int b[N];

void init(int arr[]){
  for(int i=0; i<N; i++){
	arr[i] = i;
  }
}

int main(){
  init(a);
  init(b);
  sassert(memcmp(a, b, sizeof(a)) == 0);
  return 0;
}

```

In this example, the assertion ```memcmp(a, b, sizeof(a)) == 0``` should be true, seahorn gives ```sat``` result with the commands  ```sea bpf -m64 --bmc=opsem example.c```. 
Does seahorn support ```memcmp``` function? Does it support some other memory manipulation functions, such as ```memset```, ```memcpy```, ```memmove```, ```memchr```? Extendedly, does it support the ```__builtin_```function in the ```<stdlib.h>``` library, such as ```__builtin_memcmp```, ``` __builtin_memcpy```?

**Comment by caballa** [comment]
You should see this warning message

```
Warning: unhandled instruction:   %_22 = tail call i32 @memcmp(i8* noundef nonnull dereferenceable(40) %_20, i8* noundef nonnull dereferenceable(40) %_21, i32 40) #7 @ entry in main (BvOpSem2.cc:3433)
```

So, `memcmp` is not modeled precisely.
