### ISSUE TITLE
Unexpected result about global variable.

### ISSUE THREAD

**Issue by Elowen-jjw** [seahorn/seahorn#519]
**example1:**
```
#include "seahorn/seahorn.h"

int global = 0;

void foo(int i) {
  global += i;
  sassert(global <= 2);
}

int main(void) {
  do {
    foo(1);
    if (global == 1) {
      continue;
    } else if (global == 2) {
      continue;
    }

    break;
  } while (1);

  return 0;
}
```
**example2:**
```
#include "seahorn/seahorn.h"

int global = 0;

void foo(int i) {
  global += i;
  sassert(global <= 2);
}

int main(void) {
  foo(1);
  foo(1);
  foo(1);
  return 0;
}
```
The above two examples express the same meaning, theoretically seahorn should both give ```sat```, while the result of example1 is ```unsat``` with command ```sea bpf -m64 example.c```. Please help me to explain this situation, thanks.

OS: Ubuntu 22.04
version: 14.0.0-rc0

**Comment by caballa** [comment]
This is the standard problem with bounded model checking (BMC).  
You need to tell the number of loop unrolls and if you provide a too small number then BMC is incomplete.
If the number is too small then you won't unroll enough loops so BMC can claim a program is safe but if you would unroll enough then you would find an execution that violates the property. 

By default, the BMC engine unrolls loops only one iteration. 
If you add the option `--bound=2` SeaHorn will return the expected result `sat`.  

There is an option `--assert-on-backedge` that adds the so-called unwinding assertions to make sure that loops are unrolled enough. This option typically works well but in this case `--bound=1 --assert-on-backedge` still returns `unsat`. I think there is some issue related to the fact that the loop condition is `true`.

**Comment by agurfinkel** [comment]
Also the `--inline` options inlines the function calls early in the pipeline and helps solve this instance faster.
