### ISSUE TITLE
Mismatch: BPF vs PF

### ISSUE THREAD

**Issue by yvizel** [seahorn/seahorn#539]
**Describe the bug**
A simple example is attached.
BMC (bpf --bmc=opsem) shows UNSAT while pf shows SAT -- both with bit-vector semantics.

**To Reproduce**

BMC command line: `sea bpf example.c --keep-temp --temp-dir=/tmp/ptr -S  -o /tmp/ptr/out.smt2 --inline --verbose=1  --bv-cex  --cex=cex.ll --oll=main1.ll   --show-invars --track=ptr --bv-chc --bmc=opsem`

CHC command line: `sea pf example.c --keep-temp --temp-dir=/tmp/ptr -S  -o /tmp/ptr/out.smt2 --inline --verbose=1  --bv-cex  --cex=cex.ll --oll=main1.ll   --show-invars --track=ptr --bv-chc`

**Desktop (please complete the following information):**
 - OS: Linux
 - LLVM: llvm14
 - Z3: z3-4.12.2
[example.zip](https://github.com/seahorn/seahorn/files/12886319/example.zip)

**Comment by caballa** [comment]
Did you unroll enough with BMC? What happens if you run BMC with `bound=5` or `bound=10`

**Comment by yvizel** [comment]
Yes - tried different bounds.
Bounds shouldn't really play a role in this example.

Also, the in `pf` mode the produced cex cannot be verified by the BMC engine. Again, bv semantics are used.
