### ISSUE TITLE
Seahorn misses error in programs with nested array indices

### ISSUE THREAD

**Issue by Novak756** [seahorn/seahorn#541]
**Describe the bug**
Consider the following program
```c
extern void __VERIFIER_error(void);
#define ARRAY_SIZE 4

int main(){
	long packet[ARRAY_SIZE];
	if(packet[0] >= 0 && packet[0] < 4){
		if(packet[(packet[0])] == 1){
			__VERIFIER_error(); 
		}
	}
	return 0;
}
```
Seahorn misses the `__VERIFIER_error()` and returns `unsat`, with `Warning: found 1 possible reads of undefined values`.
However due to the outer if statement, the second array access cannot be out of bound and the bug should be reachable.

**To Reproduce**
1. Say the above is called bug.c
2. `sea pf bug.c` returns `unsat`

**Expected behavior**
The error should be reachable, so it should return sat.

**Desktop (please complete the following information):**
 I used the nigthly Docker image both for llvm10 and 14
 - OS: WSL2 Linux 20.04
 - LLVM: 10 and 14
 - Z3 version 4.8.9 - 64 bit

**Comment by caballa** [comment]
As the warning says, `packet` is uninitialized because it's a local variable. Reading from uninitialized memory is undefined behavior so probably LLVM removes a big chunk of that code.

**Comment by Novak756** [comment]
Yes I can see that, however running Seahorn on something like
```c
extern void __VERIFIER_error(void);
#define ARRAY_SIZE 4

int main(){
    long packet[ARRAY_SIZE];
    if(packet[0] == 1){
        __VERIFIER_error(); 
    }
    return 0;
}
```
yields `sat` without any warnings, so I assumed the index calls would just return non-deterministic values.

**Comment by caballa** [comment]
It depends on what LLVM decides to do with UB.
You can add option `--oll=bug.ll` to see the actual LLVM bitcode that it's analyzed by SeaHorn.
