### ISSUE TITLE
Seahorn unable to find bug with bounded frontend

### ISSUE THREAD

**Issue by Novak756** [seahorn/seahorn#545]
**Describe the bug**
Running seahorn on the file bug.c returns unsat even though the __VERFIER_error() call should be reachable

**To Reproduce**
1. Link to an input file (bitcode is preferred): [input.zip](https://github.com/seahorn/seahorn/files/13674495/input_files.zip)
2. Full command line options
Unsat for
`sea bpf -m64 bug.c`
`sea bpf --inline -m64 --bmc=opsem bug.c`
and `sea bpf --inline -m64 --bmc=mono bug.c`

**Expected behavior**
The error should be reachable. See bug_runnable.c for a possible trace. Can also be confirmed with 

**Desktop (please complete the following information):**
 - OS: Nigthly LLVM14 Seahorn Docker on Ubuntu 20.04 WSL2 
 - LLVM: 14
 - Z3: Z3 version 4.8.9 - 64 bit

**Additional context**
If it helps, I also included a program (bug_noFV.c) that should be semantically equivalent (removing unnecessary copies of const_arr3) where seahorn is able to find the error.
Might therefore have something to do with the interaction between the array_comp function and the bpf frontend.

**Comment by agurfinkel** [comment]
For some reason SeaHorn cannot determine a static loop bound in this example and reverts to default bound for loop unrolling. Forcing to unroll sufficient number of times returns `sat`. The relevant option is `--bound=31`

This issue can be caught by vacuity. This requires using specialized SeaHorn assertions and enable vacuity flags. For an example, see this repo https://github.com/seahorn/verify-c-common that shows how to wire seahorn into a build system and enable such sanity checks.
