### ISSUE TITLE
seaopt affects seahorn's performance

### ISSUE THREAD

**Issue by kferles** [seahorn/seahorn#58]
While running seahorn on a small example, I observed that the optimizer might have a negative effect on seahorn.

Specifically, I am getting the following behavior:
 ```bash
$ time seahorn --keep-shadows=true --horn-solve -horn-inter-proc -horn-sem-lvl=mem --horn-step=large test.bc
sat

real    0m8.709s
user    0m8.688s
sys     0m0.012s

$ time seahorn --keep-shadows=true --horn-solve -horn-inter-proc -horn-sem-lvl=mem --horn-step=large test.o.bc
^C
real    5m35.210s
user    5m34.892s
sys     0m0.032s
```
I stopped the second run after five minutes.

I got test.o.bc by running the following:
```bash
$ seaopt -f -funit-at-a-time -o test.o.bc -O3 --enable-indvar=false --enable-loop-idiom=false --enable-nondet-init=false -disable-loop-vectorization -disable-loop-unrolling test.bc
```

Do you have any idea what might be causing this?

The input files can be found here:
* [test.bc](https://www.dropbox.com/s/j5k0viw95veo5bl/test.bc?dl=0)
* [test.o.bc](https://www.dropbox.com/s/9xir2108gkj692t/test.o.bc?dl=0)

**Comment by agurfinkel** [comment]
This is a well known issue. The optimizer might significantly change the program, making it easier or harder. On large benchmarks, the optimizer is almost always positive. On small once, the performance is very sensitive to individual benchmark. 

I have to look at this particular example to see what is going on.

**Comment by kferles** [comment]
Thanks for the quick response.

Yes, I've also noticed this behavior in other examples where the optimizer changes the program significantly. However, in this case, it only combines some instructions that affect some assume statements.

**Comment by agurfinkel** [comment]
Did not realize this was a `sat` instance! 
With optimization, `seahorn` infers more lemmas and managing those lemmas slows down loop unrolling. It needs to go to 63 steps before termination.

Many options and newer versions of spacer seem to be less sensitive to this example for some reason. You can use `--horn-flex-trace=true` which searches for longer counterexamples before increasing the search bound. It helps significantly for this example.
