### ISSUE TITLE
A latest tag of Docker image

### ISSUE THREAD

**Issue by nekketsuuu** [seahorn/seahorn#62]
When I pulled a docker image of SeaHorn, it failed.

    $ sudo docker pull seahorn/seahorn
    Using default tag: latest
    Error response from daemon: manifest for seahorn/seahorn:latest not found

There is only a tag `v1` therefore a following command succeeded.

     $ sudo docker pull seahorn/seahorn:v1

So how about creating the latest tag?

Environment: Ubuntu 14.04 LTS, Docker version 1.13.0

**Comment by lememta** [comment]
@nekketsuuu thank you for trying out SeaHorn. I have now pushed a new version of SeaHorn with 'latest' tag. https://hub.docker.com/r/seahorn/seahorn/tags/

**Comment by nekketsuuu** [comment]
@lememta Thanks for your reply! I tested the latest version. Commands like `docker run -it seahorn/seahorn /bin/bash` were successfully executed.

And I think this image is actually different from `seahorn/seahorn:v1`, right?
How about creating a new tag like `v2` in order to refer to this version in the future.
Maybe [this StackOverflow question](http://stackoverflow.com/questions/22080706/how-to-create-named-and-latest-tag-in-docker) helps you.

Anyway, this issue is fixed. Thank you!
