### ISSUE TITLE
Issue when installing seahorn

### ISSUE THREAD

**Issue by cycine123** [seahorn/seahorn#64]
I am new to both Linux and Seahorn. My computer is running Ubuntu 14.04 LTS. I was following the steps in the installation. When I typed in "cmake -DCMAKE_INSTALL_PREFIX=run ../" in the terminal. It says "Could NOT find Git (Git_Executable)". Could anyone help me to solve this problem? Thanks!

**Comment by agurfinkel** [comment]
The error means that you do not have git program installed. 

It might be difficult to compile seahorn on an older system like that. You might consider using the docker image or one of the binary releases.
