### ISSUE TITLE
If it is possible to output the domain in the format of constraints or generator?

### ISSUE THREAD

**Issue by gaobo89** [seahorn/seahorn#67]
as titled, If it is possible to output the domain in the format of constraints or generator?
for example, 
sea pf --crab-domain=int(or pk_apron)
if i want to get the polyhedra domain of newpolka or interval, is that possible?

thanks a lot.

**Comment by caballa** [comment]
Answered here https://github.com/caballa/crab-llvm/issues/15.
Note that from the seahorn's perspective, the invariants inferred by crab-llvm are translated to Expr in LoadCrab and directly injected in spacer (the back-end solver). 

But there is nothing to stop you from iterating on the constraints returned by `to_linear_constraint_system()`. 
Is there a specific use of crab-llvm invariants that you need in seahorn?
