### ISSUE TITLE
test harness example within SeaHorn tutorial

### ISSUE THREAD

**Issue by Robbin1987** [seahorn/seahorn#70]
Hi, 

I am looking into the creation of the test harness file mentioned in the SeaHorn tutorial. The issue is that my witness file (test.ll) is empty beside the moduleId and datalayout.

I use the code which is used as example in the tutorial and the following cmd: ./sea pf test.c --m64 --cex=test2.ll (the tutorial mentions -m64 and -cex=.., but that is incorrect.)

root@osboxes:/home/osboxes/Downloads# /home/osboxes/Downloads/seahorn/build/run/bin/sea pf test2.c --m64 --cex=test3.ll --horn-stats
/usr/bin/clang-3.6 -c -emit-llvm -D__SEAHORN__ -fgnu89-inline -m32 -I/home/osboxes/Downloads/seahorn/build/run/include -o /tmp/sea-9dBKh3/test2.bc test2.c
/home/osboxes/Downloads/seahorn/build/run/bin/seapp -o /tmp/sea-9dBKh3/test2.pp.bc --strip-extern=false --kill-vaarg=true /tmp/sea-9dBKh3/test2.bc
/home/osboxes/Downloads/seahorn/build/run/bin/seapp -o /tmp/sea-9dBKh3/test2.pp.ms.bc --horn-mixed-sem --ms-reduce-main /tmp/sea-9dBKh3/test2.pp.bc
/home/osboxes/Downloads/seahorn/build/run/bin/seaopt -f -funit-at-a-time -o /tmp/sea-9dBKh3/test2.pp.ms.o.bc -O3 --enable-indvar=false --enable-loop-idiom=false --enable-nondet-init=false --unroll-threshold=150 --disable-loop-vectorization=true --disable-slp-vectorization=true --vectorize-slp-aggressive=false /tmp/sea-9dBKh3/test2.pp.ms.bc
/home/osboxes/Downloads/seahorn/build/run/bin/seahorn --keep-shadows=true --horn-solve -horn-cex-pass -horn-cex=test3.ll -horn-inter-proc -horn-sem-lvl=mem --horn-step=large /tmp/sea-9dBKh3/test2.pp.ms.o.bc --horn-stats
sat

************** BRUNCH STATS ***************** 
BRUNCH_STAT Result FALSE
BRUNCH_STAT Horn 0.00
BRUNCH_STAT HornClauseDB::loadZFixedPoint 0.00
BRUNCH_STAT HornifyModule 0.00
BRUNCH_STAT LargeHornifyFunction 0.00
BRUNCH_STAT seahorn_total 0.01
************** BRUNCH STATS END ***************** 

The assert is SAT, therefore there should be a valid witness, which is as expected. I can run the debugger and see that it fails. So the ./out is successfully created, but how can the witness be empty?

Thanks in advance,

**Comment by caballa** [comment]
Please update and let me know if you still have problems generating the harness. We have also fixed the blog. Thanks!

**Comment by Robbin1987** [comment]
I rebuild SeaHorn and now the harness is successfully generated. Thanks you.
