### ISSUE TITLE
Building SeaHorn following installation guide does not work

### ISSUE THREAD

**Issue by Robbin1987** [seahorn/seahorn#72]
Hi all,

I am not able to build SeaHorn if I follow the installation instruction. The problem occurs when its building LLVM that is checked out from SVN.

The only way that I know, to be able to build SeaHorn, is to follow the steps in the Travis jobs overview. Here LLVM is extracted from dropbox. 

Is this known?

**Comment by agurfinkel** [comment]
Hey, what is the error message you are getting? In general, LLVM 3.6 that we are using is getting old and might be difficult to compile on newer systems. However, we are in process of switching to LLVM 3.8 that should make things easier.

**Comment by caballa** [comment]
I'm going to close it since we didn't hear back from Robbin1987
