### ISSUE TITLE
ABC instrumentation is not correct with -m64 option

### ISSUE THREAD

**Issue by caballa** [seahorn/seahorn#77]
- `sea pf -O0 -m32 --abc=global --dsa=sea-ci ./test/abc/test-2-false.c` returns the correct answer `sat`.
- `sea pf -O0 -m64 --abc=global --dsa=sea-ci ./test/abc/test-2-false.c` returns the wrong answer `unsat`

I think the difference is in the `align` attribute in the allocation of the array:
1) `-m32`:  ` %a = alloca [10 x i32], align 4`
2) `-m64`:  ` %a = alloca [10 x i32], align 16`

For 1) our pass calculates that the size of the array `%a` is 40. 
For 2) our pass calculates that the size of the array `%a` is 48.

In `test-2-false.c`, for the statement ` read(a[(nd()>0?i-1:i)]);`:
the access `a[i]` would be translated to something similar like this:

1) `assert(40+4 <= 40)`  (with `-m32`)
2) `assert(40+4 <= 48)`  (with `-m64`)

where `40` from the lhs of the leq operator is the value of `i` and `4` is the size of the array element.  The `40` (`48`) from the rhs of the leq operator is the size of the array.

That's why with `-m64` we report incorrectly that the program is safe.

We need to adjust the sizes of allocated memory taking the alignment into consideration.

The size of allocated memory is inferred by the function `getObjectSize` in `seahorn/lib/Transformations/BufferBoundsCheck.cc`. It's almost a copy of the one defined in llvm. I don't remember now why we made a copy but we needed to make some modification to it. To use the one defined by llvm changes nothing. Note also that this adjustment is needed in all the encodings `Local`, `Global` and `GlobalCCallBacks`.

**Comment by kuhar** [comment]
Everything seems to be OK until the execution enters `ObjectSizeOffsetVisitor::visitAllocaInst` in `MemoryBuiltins.cpp`.
`visitAllocaInst` correctly checks that the size is 40 and the alignment is 16, and then we hit a return:
`return std::make_pair(align(Size, I.getAlignment()), Zero);` in line 440.

40 gets aligned to 48 (3 * 16).

The computation of alloca size starts in `BufferedBoundsCheck.cc`.
It seems like aligning the size might not be the thing we want here, but what confuses me is that there are multiple other uses of align within `BufferedBoundsCheck.cc`. Now, I also see that there is a flag for rounding to alignment in getObjectSize (`BufferedBoundsCheck.cc:419`), and is set to `true` and not passed anywhere the same time.

What is the logic supposed to be like here? IE when do we need to return aligned size and when not?

**Comment by agurfinkel** [comment]
@caballa , our `getObjectSize` takes into account `dereferenceable` attribute. The one in LLVM does not.
Since there are no such attributes in this example, using either one is ok.

**Comment by agurfinkel** [comment]
I think there is no bug here. We need to check whether an access falls outside of the allocated region.
The size of the region is determined by the size of the structure being allocated (40 bytes for the array in this case), plus any alignment that happens to be added by the allocation instruction (`alloca` in this case).

On a 32-bit platform, `alloca` of 40 bytes returns 40 bytes (alignment of 4). 
On a 64-bit platform, `alloca` of 40 bytes returns 48 bytes (alignment of 16).

Son on a 64-bit platform there is an extra word at the end of the array, so accessing past the end of an array is not an overflow. This is cute :smile:

So the question is do we want to indicate an error when array is accessed out of its declared size, or when memory is accessed past its allocation. Both are interesting, but for different reasons.

In the first case, we might leak sensitive information (like the heartbleed bug), in the second we are likely to get a crash. 

@caballa , let me know if you agree and close.

**Comment by agurfinkel** [comment]
@kuhar , for the current mode, we should return aligned size whenever the allocation is known to be aligned (i.e., `alloca` or global).

**Comment by caballa** [comment]
@arie: agreed. I'll close the issue.
