### ISSUE TITLE
Pre-building dependencies

### ISSUE THREAD

**Issue by agurfinkel** [seahorn/seahorn#78]
Pre-build dependencies for most common platform and host them on
github under `seahorn/deps`. The dependencies are

* `LLVM 3.8`
* `z3/spacer` branch `spacer3` from (https://bitbucket.org/spacer/code)
* `lib-boost 1.62`

The common platforms are Ubuntu 14.04 and 16.04, 32bit and 64bit,
Release and Debug.

There should be Docker scripts to automate rebuilding the
dependencies. For example, each configuration has a `Dockerfile` such
that running docker on it produces packaged dependencies.

The docker container for building the dependencies can start from
[buildpack-deps](https://hub.docker.com/_/buildpack-deps/).

For example, see docker container for Python
(https://hub.docker.com/_/python/).

**Comment by kuhar** [comment]
Is the purpose of prebuilding dependencies with docker to:
1) create a Dockerfile that will be included in another Dockerfile that at the end will produce SeaHorn container,
2) create an environment with llvm binaries available,
3) produce a bunch of llvm binaries and configurtion files that will be copied from the container to some other place?

I don't fully get how this task fits into the bigger picture.

So far I played with docker a bit and came up with this script for building llvm + clang on xenial:
```bash
#
# llvm-3.8 xenial Dockerfile for SeaHorn
#

# Pull base image.
FROM buildpack-deps:xenial

# Install deps
RUN \
  apt-get update && \
  apt-get install -yqq binutils-gold cmake ninja-build libiomp-dev

RUN update-alternatives --install "/usr/bin/ld" "ld" "/usr/bin/ld.gold" 20
RUN update-alternatives --install "/usr/bin/ld" "ld" "/usr/bin/ld.bfd" 10

# Define working directory.
WORKDIR /llvm

RUN mkdir -p /llvm/repo
WORKDIR /llvm/repo

RUN git clone https://github.com/llvm-mirror/llvm/ ./ -b release_38 --depth=1
WORKDIR /llvm/repo/tools

RUN git clone https://github.com/llvm-mirror/clang -b release_38 --depth=1
RUN mkdir -p /llvm/build
WORKDIR /llvm/build

RUN cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD="X86;" \
          -DCMAKE_INSTALL_PREFIX:PATH=/llvm ../repo
RUN ninja install

WORKDIR /llvm
RUN rm -rf /llvm/build

# Define default command.
CMD ["bash"]
```

**Comment by kuhar** [comment]
With https://github.com/seahorn/seahorn/pull/90, that should be it for this issue.

**Comment by agurfinkel** [comment]
compiling seahorn in docker is next :)
