### ISSUE TITLE
C++ mangled names

### ISSUE THREAD

**Issue by roachspray** [seahorn/seahorn#85]
I am uncertain of the level of desire for C++ support, so please let me know if I should not think about this stuff. There is the expectation in some of the seahorn passes that names be in C naming form (not mangled), so the compiler emitting _Z17__VERIFIER_assumei, etc causes analysis to fail because the PromoteVerifierCalls pass skips over these. I am guessing two ways to handle this... one is a hack that I have made a pull request for. The other is doing another pass that can be invoked to do a rename:

```
/** Rename certain C++ mangled functions of interest */

#include "llvm/Pass.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/IR/Value.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
using namespace llvm;
namespace seahorn
{
  class CppRename : public ModulePass
  {
    std::map<std::string, std::string> mangledMap = {
      std::make_pair("_Z17__VERIFIER_assumei", "__VERIFIER_assume"),
      std::make_pair("_Z16__VERIFIER_errorv", "__VERIFIER_error")
// Insert others that might be mangled that are wanted in a certain form
    }; 
   public:
    static char ID;
    CppRename () : ModulePass (ID) {}
    bool runOnModule (Module &M)
    {
      bool changed = false;
      for (auto ii = mangledMap.begin(); ii != mangledMap.end();
       ++ii) {
        std::string fname = *ii; 
        Function *f = M.getFunction(fname);
        if (f != NULL) {
          f.setName(mangledMap[fname]); 
          changed = true;
        }
      }
      return changed;
    }
    void getAnalysisUsage (AnalysisUsage &AU)
    { }
    virtual const char* getPassName () const 
    {return "Rename certain C++ mangled naming for later use";}
  };
  char CppRename::ID = 0;
  Pass* createCppRenamePass (){
    return new CppRename ();
  }
}
```
Or likely there is another generic way to do it with cxxabi. 

The hack pull req is https://github.com/seahorn/seahorn/pull/86

**Comment by agurfinkel** [comment]
The proper way to handle it to make sure that verifier-specific functions are declared as `extern "C"`. There is a standard way to call C functions from C++. Just follow it.

**Comment by roachspray** [comment]
Yes, my fault. I was over thinking a use case that I had... which did not make sense. Sigh. Sorry to waste your time (and mine!).
