### ISSUE TITLE
ashr

### ISSUE THREAD

**Issue by caterinaurban** [seahorn/seahorn#9]
I think that the ashr instruction is not interpreted correctly.
For example:

ashr i32 -1, 31 

should not return -1 as a result.

********* C code *********

extern int nd (void);
extern void __VERIFIER_error (void);
void assert (int v) { if (!v) __VERIFIER_error (); }
extern void __VERIFIER_assume (int);
#define assume __VERIFIER_assume

int main() {
    int x = nd();	
    int r = x < 0 ? -x : x;
    while (x != 0) {
        r = r - 1;
        if (! (r >= 0)) __VERIFIER_error();
            if (x < 0) {
                x = x + 1;
            } else {
                x = x - 1;
            }
    }
    return 0;
}

********* LLVM Code *********

define i32 @main() #1 {
entry:
  %_0 = call i32 @nd() #3
  %_1 = icmp slt i32 %_0, 0
  %_2 = sub nsw i32 0, %_0
  %_3 = select i1 %_1, i32 %_2, i32 %_0
  br label %_bb

_bb:                                              ; preds = %_bb3, %entry
  %x.0.i = phi i32 [ %_0, %entry ], [ %x.1.i, %_bb3 ]
  %r.0.i = phi i32 [ %_3, %entry ], [ %_10, %_bb3 ]
  %_5 = icmp eq i32 %x.0.i, 0
  call void @verifier.assume.not(i1 %_5)
  br label %_bb1

_bb1:                                             ; preds = %_bb
  %_7 = icmp sgt i32 %r.0.i, 0
  br i1 %_7, label %_bb3, label %_bb2

_bb2:                                             ; preds = %_bb1
  br label %verifier.error

_bb3:                                             ; preds = %_bb1
  %_10 = add nsw i32 %r.0.i, -1
  %_11 = ashr i32 %x.0.i, 31
  %_12 = and i32 %_11, 2
  %_13 = add nsw i32 %_12, -1
  %x.1.i = add i32 %x.0.i, %_13
  br label %_bb

verifier.error:                                   ; preds = %_bb2
  ret i32 42
}

********* SeaHorn (Wrong) Counterexample *********

TRACE BEGIN
_bb C
_bb C
verifier.error C
TRACE END
Solver: sat
entry: 
  %_0 -1
  %_1 true
  %_2 1
  %_3 1
_bb: 
  %x.0.i -1
  %r.0.i 1
  %_5 false
_bb1: 
  %_7 true
_bb3: 
  %_10 0
  %_11 -1 <--- should be the negative i32 number 111...111 (I think)
  %_12 3  <--- should be 2
  %_13 2  <--- should be 1
  %x.1.i 1  <--- should be 0
_bb: 
  %x.0.i 1
  %r.0.i 0
  %_5 false
_bb1: 
  %_7 false
_bb2:

**Comment by agurfinkel** [comment]
ashr is not really supported. The next culprit is 32bit AND (register _12).

The underlying problem is probably some optimization. I can reproduce it,
so will see if I can fix it quickly.

cheers,
arie

**Comment by agurfinkel** [comment]
Fixed by disabling an optimization in llvm-seahorn.
